== La Vida de Francis Howgill

Desde los doce años, determiné en mi corazón conocer al Dios que el mundo profesaba,
y respecto a quién había leído en las Escrituras, a quién Abraham, Noé, Moisés,
los Profetas y el resto de los Padres adoraron,
y me uní a la forma de adoración más estricta que había
en el lugar donde vivía. A menudo deseaba estar solo,
y le daba mucho tiempo a la lectura y a la meditación.
Y cuando me mantenía sobrio y serio,
pasando tiempo solo, comenzaba a ver que todos los entretenimientos y pasatiempos,
y este tipo de cosas en las que los jóvenes se deleitaban, eran vanidad,
y que duraban solo por un momento.
Pero cuando caía en la locura y en el desenfreno, y hacía estas cosas,
esa naturaleza que había corrido a la transgresión se complacía en ellas;
pero inmediatamente después de que me alejaba de estas cosas,
me sentía juzgado en mi corazón por lo que había hecho, y esto a menudo me hacía llorar.
Entonces determinaba, en mi voluntad, nunca volverlo a hacer,
y por un tiempo me restringía de practicar esas cosas en las que había andado.
Pero tan pronto como volvía a estar entre mis compañeros,
hacía esas cosas que antes había visto claramente que eran vanidad,
y por las que había sido reprendido y reprobado.

Y así vivía, a menudo sintiendo condenación en mi corazón cuando era serio,
y no pudiendo encontrar paz.
Y sin saber qué hacer,
deseaba estar en un lugar solo donde no pudiera escuchar
ni ver a nadie haciendo alguna locura,
y donde no pudiera correr a las antiguas prácticas,
aunque algo en mí realmente las deseaba mucho.
Pero cuando no cedía a estos deseos, sentía alegría y tenía paz,
y comencé a oponerme a mis amigos con los cuales había andado en desenfreno.
Entonces estos empezaron a injuriarme, y a aborrecerme y a despreciarme; sin embargo,
nada de esto me importaba en ese momento.
También leía mucho y oraba frecuentemente en palabras, tres o cuatro veces al día,
aunque no sabía dónde estaba Dios, sino que todavía caminaba en mi imaginación,
imaginando a un Dios muy distante, y así continué por un tiempo.
Así empecé a crecer en el conocimiento externo (que es natural) y por ello me envanecí,
porque el mundo me admiraba.
Sin embargo, a menudo era condenado por mis palabras y acciones vanas,
y veía que la raíz de iniquidad seguía creciendo
en mí. Así que seguí un curso de vida más estricto,
y a menudo iba, cinco o seis millas,
a escuchar los sermones más excelentes (como eran considerados),
y entonces caí más profundamente en una religión de palabras,
pero todavía era el mismo de corazón; no, era peor,
porque este conocimiento externo me envanecía.

Cuando tenía unos quince años,
a menudo corría de un lado a otro en busca de los sermones más excelentes,
y así supe quiénes eran todos los Cristianos eminentes (así llamados) de la región
en la que vivía. Fui despreciado por mis padres y por el mundo,
y un gran oprobio cayó sobre mí, pero yo podía ver que ellos no sabían nada de Dios,
y por eso no me importaba mucho.
Una gran tristeza vino sobre mí durante cuatro o cinco años,
y cuando me volvía hacia mi interior, era juzgado por toda mi pasada iniquidad,
y se me mostraba que mi corazón todavía era corrupto.
Sin embargo, a medida que me mantenía vuelto internamente a la luz en mi conciencia,
era restringido de muchas acciones que sentía deseo de hacer.
Y en el mismo momento cuando había estado haciendo algo injusto en acciones o palabras,
a menudo era detenido, y cuando veía que había sido preservado del mal,
un gran gozo se levantaba en mí;
y sin embargo cuando había hecho alguna cosa apresurada y precipitadamente,
me sentía juzgado.
Pero los maestros me decían que lo que me guardaba del pecado y me restringía de cometerlo
era solo una "`conciencia natural,`" y lo llamaban "`una gracia que restringe`" y no
"`una gracia que salva,`" e insistían en que quién la tenía solo era un demonio domado.

Y entonces escuché sus imaginaciones y desprecié la luz como algo muy débil y pequeño,
creyendo que no era más que "`una gracia común`" que preservaba de pecados graves,
pero que los santos tenían otro tipo de fe y gracia.
Y luego me hablaron de cómo los santos creían en Cristo
de tal modo que sus pecados no les eran imputados,
sino que al contrario Su justicia les era atribuida,
y que por lo tanto yo debía buscarlo a través de los medios provistos,
como orar y recibir el sacramento (como ellos lo llamaban).
Pero yo tenía mucho miedo de comer de Él indignamente,
y nadie podía mostrarme qué realmente era el cuerpo de Cristo.
Ellos decían que yo solo debía creer que Él sufrió por mí;
y en verdad yo sí creía todo lo que ellos llamaban su "`fe,`" pero aun
así no podía ver cómo la muerte de Cristo había removido todo mi pecado,
porque el testigo en mi conciencia me decía que mientras siguiera pecando,
seguía siendo un esclavo del pecado.
Y ellos me decían que no debía omitir la ordenanza de la Cena del Señor,
porque a través de ella se recibía fuerza y se añadía fe; pero yo estaba muy confundido,
porque por un lado ellos me imponían esto como un deber,
y por otro lado veía que la Escritura decía, "`El que come indignamente,
juicio come para sí.`"^
footnote:[1 Corintios 11:29]
Así continué en temor, aunque nadie me podía acusar de ningún mal externo.

Y un tiempo después de esto vino sobré mí un gran
temor de que había pecado contra el Espíritu Santo,
y cayó sobre mí una gran angustia.
Entonces los "`médicos nulos`"^
footnote:[Job 13:4]
dijeron que no había venido preparado a la mesa del Señor,
aunque tenía toda la preparación de la que ellos habían hablado.
Por lo tanto, ayuné y oré, y anduve afligido en dolor,
y pensaba que no había nadie como yo, ya que me sentía tan tentado por todos lados.
Corría a este hombre y al otro, y ellos me aplicaban las promesas de la Escritura,
pero veía que eran solo palabras,
porque el testigo de Cristo me mostraba que la raíz de iniquidad todavía seguía en pie,
y que el cuerpo de pecado permanecía. Sin embargo,
era preservado por Su poder secreto de males obvios, pero aun así el dolor me rodeaba,
y dudaba de todo lo que supuestamente había recibido,
lo cual ellos decían que era la gracia, el arrepentimiento y la fe.

Entonces les dije que todavía había culpa en mí; y ellos dijeron,
"`Todo pecado ha sido removido por Cristo,
pero la culpa permanecerá mientras vivamos;`" y para confirmarme esto,
ellos me mostraron en las Escrituras algunas de las condiciones
de los santos que todavía estaban en la batalla.
Entonces dije dentro de mí, "`Esta es una salvación miserable,
si la culpa y la condenación por el pecado deben permanecer
en mí;`" y así era llevado de monte en collado.
Pero vi que ellos predicaban confusión,
así que cada vez me importaba menos lo que hablaban, y decía en mi corazón,
"`Sin duda este no es el verdadero ministerio de Cristo.`"
Así que por largas temporadas dejé de escuchar a estos maestros y no les presté atención,
y en lugar de ello me mantuve en casa, y caminaba por lugares desérticos llorando solo.
Todo lo que había hecho era puesto delante de mí,
y sentía como si cada pensamiento fuera juzgado,
hasta que mi corazón se ablandaba y quebrantaba.
Y cuanto más me afligía, más paz tenía, porque algo del Señor hablaba dentro de mí,
aunque en ese entonces no lo conocía.

Pero los maestros en aquellos días decían que era herejía
esperar que la Palabra del Señor fuera declarada ahora,
y que solo se podía encontrar en la letra;
por esto no le presté mucha atención a esa Palabra que está cerca,
en la boca y en el corazón.^
footnote:[Romanos 10:8; Deuteronomio 30:14]Sin embargo,
algunas veces fui movido a hacer cosas justas directamente
por el poder y Palabra de Dios,
y entonces brotaba la paz y el gozo en mi corazón,
y se pronunciaba una promesa en mi corazón de que Él mismo me enseñaría, y sería mi Dios.
Y a menudo obedecía Su voz en contra de mi propia voluntad, y así negaba mi voluntad;
pero ellos me decían que obedecer por temor era legalismo,
y que era un yugo de esclavitud.
Así, escuchándolos, me levanté por encima del temor,
y realicé las cosas anteriores que ellos llamaban "`ordenanzas`" y "`obediencia
evangélica,`" diciendo que Cristo ya lo había hecho todo.

Entonces me pareció que había más belleza en aquellos que eran llamados Independientes,
y los amé, y me uní a ellos;
y todo el dinero que podía conseguir lo usaba para comprar sus libros.
Así que por un tiempo anduve con ellos y creía que ellos
eran un pueblo que estaba más separado del mundo,
porque hablaban mucho de separación. Pero finalmente me di cuenta de que eran solo palabras,
porque vi que actuaban en su propia voluntad,
y escogían a sus propios miembros y ministros,
y así hacían su propia imagen y se arrodillaban a adorarla.
Sin embargo, había algo de ternura en ellos al principio,
pero su doctrina era la misma que la del resto del mundo, a saber,
palabras externas que describían las condiciones de otros hombres.

Entonces me pareció que aquellos que eran llamados Anabaptistas tenían mayor gloria,
y caminaban más acorde a las Escrituras,
practicando las cosas que habían sido escritas externamente.
Así que fui a ellos, y había algo en ellos que amaba;
pero después ellos negaron a todos excepto a aquellos que andaban en su camino,
y decían que todos los demás estaban fuera de la
comunión de los santos y de la doctrina de Cristo.
Y finalmente vi que su fundamento era el mismo que los demás,
y que su doctrina era sostenida fuera de la vida,
aunque ellos se habían separado y habían hecho otra semejanza.
Pero todos estaban de acuerdo en que la letra escrita era la Palabra y la regla,
y que Cristo, de forma externa, lo había consumado todo;
algunos de ellos creyendo en el libre albedrío y otros oponiéndose a esto,
pero todos viviendo en sus propias voluntades.

Aun así, por un tiempo amé a aquellos que caminaban honestamente entre ellos.
Pero, aunque había entendido y estado de acuerdo con todo
lo que había oído (a excepción de su figura del bautismo,
que vi que era externa, y que era su más grande gloria,
ante la cual querían que todos se inclinaran,
o de lo contrario no podían tener comunión), aun así,
no encontré ninguna paz ni guía. Entonces algunos predicaron
la doctrina de la gracia gratuita (como ellos la llaman),
a saber, que todo pecado, pasado, presente y futuro, había sido quitado,
y que el hombre solo debía creer que todo había sido consumado.
Así ellos le predicaban salvación a la primera naturaleza,
y a la serpiente que gobierna en la carne.
Esto escuché un poco, y por lo tanto perdí mi condición interna.
Pero, aun así, dondequiera que iba, esta palabra daba vueltas dentro de mí:
"`Tú eres esclavo de aquel a quién obedeces.`"^
footnote:[Romanos 6:16]
Y así, siendo vencido por el pecado, experimentaba condenación y no justificación en mí.

Luego había algunos que predicaban a Cristo internamente,
aunque ellos mismos permanecían en lo externo, teniendo solo palabras verdaderas.
Ellos decían que todo debe ser interno (a cuya verdad mi corazón se aferró),
y hablaban de una redención interna, y de una justificación interna,
y de Dios apareciendo dentro del hombre para vencer el poder del diablo.
Y la luz en mi conciencia daba testimonio de que debía ser así,
y me sentía sumamente impulsado a esperar en el Señor para experimentarlo.
En verdad, algo en mí anhelaba al Dios viviente,
y yo sentía un verdadero amor por todos los que caminaban
honestamente en cualquier denominación,
y aborrecía que los hombres se injuriaran unos a otros, y se golpearan unos a otros,
y se persiguieran unos a otros,
y siempre tomaba el lado de los que sufrían. Pero aun así veía que,
aunque estas personas decían que todas las cosas eran internas,
y hablaban de un poder por venir, sin embargo, no experimentaban nada de lo que hablaban,
porque ellos manifestaban los mismos frutos de la carne.

Finalmente vi que ninguno andaba como un verdadero ministro de Cristo;
que ninguno de los que asumía el ministerio había recibido un don para ello,
ni el pastor, ni el maestro,
ninguno de ellos era un ministro como en el tiempo de los apóstoles.
Así que, habiendo ido a todas partes, corriendo apresuradamente de aquí para allá,
vi que todos los maestros del mundo buscaban lo suyo propio,
y alimentaban a los pobres hombres con palabras muertas y con engaño,
y que estos no eran los ministros de Cristo.
Vi que todos los que no perseveraban en la doctrina de Cristo estaban en el engaño,
y por lo tanto me separé de la mayoría de ellos,
y me di cuenta de que mientras no estuviera de acuerdo con su juicio,
ellos me odiarían y me perseguirían.

Pero finalmente, fue revelado en mi corazón que el Señor enseñaría a Su pueblo Él mismo.
Así que esperé, y muchas cosas se abrieron en mí respecto a un tiempo que estaba cerca.
Y a veces cuando oía a un sacerdote, era movido por el Señor,
y Su Palabra en mí hablaba y se oponía a lo que había oído;
y a menudo ardía como un fuego, y un temblor caía sobre mí; sin embargo,
tenía miedo del oprobio,
y por eso negaba la inspiración del Señor. Y fue
revelado en mi corazón que esperara en Él,
y que así llegaría a conocer Su consejo.

Y la Palabra del Señor estaba en mí,
y me decía que estaba cerca el tiempo en que los muertos oirían la voz del Hijo de Dios;
la cual ardía en mí como un fuego mostrándome que estaba cerca el día en que
ya no se diría "`helo aquí,`" ni "`helo allá,`" sino que todo Su pueblo sería
enseñado por el Señor. Pero aún así mi mente corría a lo externo,
y salía del temor a la ligereza, porque todavía no conocía la cruz de Cristo.
Sin embargo, esto puedo decir,
yo era más sabio que todos los maestros con los que
me encontré en esa generación. No me glorío en ello,
porque la condenación ha pasado sobre esta sabiduría para siempre.
Aún así, cuando mi mente estaba vuelta a la luz,
recibía revelaciones y profecías puras de cosas por venir,
y una creencia de que yo vería ese día, y daría testimonio de Su nombre.
Pero algunas veces cuando las verdades se revelaban muy rápido,
la sabiduría de la carne las tomaba,
y entonces corría de un lado a otro predicando contra todo ministerio.
También salí corriendo a predicar por todo el territorio
algo que había sido revelado para mí mismo,
respecto a la plenitud que estaba en el odre viejo, y por esto se maravillaban de mí,
y era admirado por muchos que andaban perdidos de monte en collado como yo.
Pero nos alimentábamos unos a otros con palabras,
y sanábamos las heridas unos a otros con engaño,
y por esto todos nosotros quedamos sepultados en dolor cuando fue
manifestado el día del Señor. Porque en ese día yo fui derribado,
y mi fundamento fue barrido,
y tanto mi justicia como mi injusticia fueron juzgadas y pesadas,
y todo fue hallado muy liviano.

Pero apenas escuché a uno declarar que la luz de
Cristo en el hombre es el camino a Cristo,
creí en la eterna Palabra de la verdad;
y la Luz de Dios en mi conciencia certificó esta doctrina.
Así que no solo yo,
sino muchos cientos más (que estaban sedientos del Señor pero que
habían sido traicionados por la sabiduría de la serpiente),
se vieron a sí mismos fuera del fundamento,
y todas nuestras bocas fueron puestas en el polvo.
En verdad, todos nos sentíamos condenados en nuestro corazón,
y vimos nuestra desnudez y teníamos vergüenza;
y aunque nuestra gloria había llegado a ser grande ante los ojos del mundo,
ahora veíamos que todo era vanidad,
y que no conocíamos el primer principio de la verdadera religión.

[.asterism]
'''

+++[+++__Nota del Editor:__
Parece que este gran despertar en el corazón de Francis
Howgill tuvo lugar en el año 1652.
Él estaba en una feria en Sedburgh, al oeste de Yorkshire,
por donde George Fox pasó declarando el día del Señor. Después de esto,
George Fox fue al patio de la iglesia,
y muchas personas que estaban en la feria fueron a él,
con muchos sacerdotes y profesantes de religión. Allí él declaró
la verdad eterna del Señor y la palabra de vida por varias horas;
mostrando que el Señor había venido a enseñarle a Su pueblo Él Mismo,
y a sacarlos de los caminos y maestros del mundo,
y que estos maestros eran como aquellos de la antigüedad
que fueron condenados por los profetas,
por Cristo, y por los apóstoles.
Él exhortó a las personas a salir de los templos hechos con manos,
y a esperar recibir el Espíritu del Señor,
para que pudieran sentir sus propios corazones como los templos de Dios.
Ninguno de los sacerdotes abrió su boca contra lo que Fox declaró;
pero finalmente un capitán dijo: "`¿Por qué no quieres entrar a la Iglesia?
Este no es un lugar adecuado para predicar.`"
George Fox le dijo que él negaba su iglesia.
Entonces Francis Howgill se levantó (quién no había visto a George Fox antes),
y se encargó de responderle al capitán. Él muy pronto lo puso en silencio,
y entonces dijo respecto a Fox,
"`Este hombre habla con autoridad y no como los escribas.`"

El siguiente relato de esta extraordinaria reunión, en la cual, Francis Howgill,
John Audland, John Camm, Richard Hubberthorne,
y muchos otros fueron convencidos de la verdad eterna,
es extraído del diario de George Fox.

[quote]
____
"`El siguiente Primer-día, vine a la capilla de Firbank, en Westmoreland,
donde Francis Howgill y John Audland habían estado predicando en la mañana.
En ese momento la capilla estaba tan llena de personas, que muchos no podían entrar.
Francis dijo que había creído que yo me había asomado a la capilla,
y que su espíritu estuvo a punto de desfallecer,
estando tan sorprendido por el poder del Señor; pero yo no me asomé. Ellos se apuraron,
y terminaron rápidamente; y ellos y algunas de las personas se fueron a cenar,
pero una gran cantidad de personas se quedó hasta que volvieron.
John Blaikling y otras personas vinieron a mí,
y me pidieron que no reprendiera a estos hombres públicamente;
porque ellos no eran maestros asalariados, sino hombres tiernos.
Yo no pude decirles si lo haría o no,
aunque en ese momento no sentía ninguna inclinación a declarar públicamente contra ellos;
pero les dije que ellos debían dejar que obedeciera los movimientos del Señor.

Mientras otros habían ido a cenar, fui a un arroyo, tomé un poco de agua,
y regresé y me senté en lo alto de una roca, cerca de la capilla.
Por la tarde,
la gente y varios de sus predicadores se reunieron alrededor
de mí. Se estimaba que había más de mil personas,
a las que les declaré la verdad eterna y palabra de vida libre y largamente,
por aproximadamente tres horas, dirigiendo a todos al Espíritu de Dios en ellos,
para que se convirtieran de las tinieblas a la luz, y creyeran en ella;
y así se volvieran hijos de ella, y fueran llevados a toda verdad,
y entendieran por experiencia las palabras de los profetas, de Cristo y de los apóstoles.
Y para que todos conocieran a Cristo como su maestro para instruirlos,
como su consejero para dirigirlos, como su pastor para alimentarlos,
como su obispo para apacentarlos,
y como su profeta para revelarles los misterios divinos;
y experimentaran sus vasijas preparadas,
santificadas y convertidas en templos adecuados para la morada de Dios y Cristo.

En las revelaciones de la vida celestial, les expliqué los profetas,
y las figuras y sombras, dirigiéndolos a Cristo la sustancia.
Entonces abrí las parábolas y dichos de Cristo,
y cosas que por mucho tiempo habían estado escondidas;
mostrando la intención y el alcance de los escritos de los apóstoles.
También revelé el estado de la apostasía que había
continuado desde los días de los apóstoles,
demostrando cómo los sacerdotes habían tomado las Escrituras,
pero no estaban en el Espíritu que las había dado,
sino que hacían mercadería con las palabras de hombres santos,
y se encontraban en los pasos de los falsos profetas, los principales sacerdotes,
los escribas y los fariseos de la antigüedad,
y eran como aquellos contra los cuales los verdaderos profetas,
Cristo y Sus apóstoles habían clamado.
Muchas personas mayores entraron en la capilla y miraban a través de las ventanas,
pensando que era algo extraño ver a un hombre predicar sobre una colina o un monte,
y no en su iglesia, como ellos la llamaban.
Al percibir esto fui movido a informarles a las personas
que la casa del campanario y el terreno sobre el que estaba,
no eran más santos que esta colina; y que esos templos,
que ellos llamaban "`las solemnes casas de Dios`" no fueron
establecidos por mandato de Dios ni de Cristo;
ni sus sacerdotes fueron constituidos por Dios como lo fue el sacerdocio de Aarón;
ni sus diezmos fueron designados por Dios como lo fueron aquellos entre los judíos;
y que Cristo ya había venido, y les había puesto fin al templo y a esa adoración,
y a sus sacerdotes y a sus diezmos,
y que ahora todos debían oírlo a Él. Porque Cristo dijo:
'`Aprended de Mí.`' Y Dios dijo de Él: '`Este es Mi Hijo amado,
en quien tengo complacencia;
a Él oíd.`' Declaré que el Señor Dios me había enviado a predicar
entre ellos el evangelio eterno y la Palabra de Vida,
y a sacarlos de todos estos templos, diezmos,
sacerdotes y rudimentos del mundo que habían surgido desde los días de los apóstoles,
y que habían sido establecidos por aquellos que se habían desviado
del Espíritu y poder en los que se encontraban los apóstoles.
Muy grandes fueron las revelaciones que tuve en esta reunión;
el poder convincente del Señor acompañó mi ministerio,
y alcanzó los corazones de las personas,
por lo cual todos los maestros de esa congregación (que eran muchos) y también
una gran cantidad de personas fueron convencidas de la verdad eterna de Dios.`"
____

[.offset]
Volviendo al relato de Francis Howgill:]

[.asterism]
'''

Entonces a medida que volvía mi mente internamente a la
luz de Jesucristo con la que había sido alumbrado,
la cual antes me había reprobado por toda mi vanidad; y también,
a medida que abrazaba y reconocía su testimonio contra mí,
esta luz me guiaba a la justicia.
Porque cuando me volvía a ella,
veía que ella era el testigo fiel y verdadero de Jesucristo, y mis ojos eran abiertos,
y todo cuanto había hecho era traído a mi memoria, y el arca del pacto era abierta en mí,
y había truenos y relámpagos y grande granizo.
Entonces la trompeta del Señor sonó en mi corazón, y nada sino guerra,
rumores de guerra y el temible día del Señor venían sobre mí, con plagas y hambre,
miedo y terror, llanto y dolor,
debido a las cosas que había visto con mis ojos y oído con mis oídos.
En la mañana deseaba que fuera de noche, y en la noche deseaba que fuera de día,
y no tenía reposo, sino tribulación por todas partes,
porque todo cuanto había hecho estaba siendo juzgado y condenado,
y vi que todo lo que había hecho en la carne estaba
bajo maldición. Entonces el león sufrió hambre,
y los sellos fueron abiertos,
y siete truenos emitieron sus voces en mí. Mis ojos fueron oscurecidos por el llanto,
mis huesos fueron secados, y mis tendones fueron contraídos.
Me convertí en un proverbio para todos, sí, los que habían sido cercanos a mí,
ahora se mantenían lejos de mí; y a medida que era derramado un ay tras otro,
las columnas de mis cielos fueron conmovidas, y mi tierra se tambaleaba como una choza.
Busqué la muerte en ese día, y no pude encontrarla,
porque huía de mí. Busqué cubrirme de alguna manera, o con cualquier cosa,
pero nada pudo hacerlo,
porque la indignación del Señor había venido sobre la bestia y el falso profeta;
y en ese día Babilonia, la madre de las rameras, vino en memoria delante de Dios,
y el mar se secó, y todos los mercaderes que habían comerciado con ella se pararon lejos,
porque la copa de la ira del Señor había sido derramada.
Entonces vi y entendí a Caín,
y encontré la naturaleza de Judas que traiciona al Señor de vida.
Yo habría corrido en cualquier dirección para esconderme,
pero no encontré nada más que lloro y crujir de dientes, dolor y terror.
Así que gemí a causa de la conmoción de mi corazón,
porque mi reino estaba lleno de oscuridad.
No sabía distinguir mi mano derecha de la izquierda, y me volví un completo tonto,
que no sabía nada, como un hombre que se había vuelto loco.

Oh, todo fue trastornado, y sufrí la pérdida de todo;
porque vi que todo cuanto había hecho había sido hecho en la naturaleza anatema.
Sin embargo, algo clamaba en mí, "`¡Justos y verdaderos son Tus juicios, oh, Señor!`"
Mi boca fue detenida, y no me atrevía a mencionar Su nombre.
Pero a medida que soportaba la ira del Señor, algo en mí se regocijaba,
y la cabeza de la serpiente comenzó a ser herida,
y los dos testigos que habían sido asesinados,
fueron resucitados en mí. Y entonces vi el tribunal de Cristo,
y como se tenía que dar cuentas, y que en ese momento Esaú sería maldecido,
y la naturaleza de Caín, Judas, Ismael,
y de todos los cananeos y egipcios sería echada con las cabras a Su mano izquierda.
Y a medida que el juicio era declarado, algo en mí seguía clamando, "`Justo eres Tú, oh,
Señor, ¡en todos Tus Juicios!`"
Y cuando entregué todo al juicio, la semilla cautiva salió de la prisión y se regocijó,
y mi alma se llenó de gozo, y llegué a ver a Aquel a quien había traspasado,
y entonces mi corazón fue quebrantado.
Y luego, finalmente vi y entendí la cruz de Cristo, y permanecí en ella,
y por ella la enemistad fue matada progresivamente, y el nuevo hombre fue creado,
y así se hizo la paz.

Así la vida eterna fue introducida por medio de muerte y juicio,
y yo recibí ese don perfecto que es dado por Dios;
porque la ley santa de Dios me fue revelada, y fue escrita en mi corazón,
y Su temor y Su palabra que antes habían matado ahora vivificaban.
Sí, le agradó al Padre revelar a Su Hijo en mí a través de la muerte,
de modo que llegué a experimentar la purificación por Su sangre que es eterna.
Así que ahora tengo descanso y paz haciendo la voluntad de Dios,
y he entrado en el verdadero descanso,
y me he acostado en el redil de Dios con Sus corderos,
donde Sus hijos se regocijan juntos,
y los santos guardan sus días santos ¡Gloria a Él para siempre!

He escrito estas pocas cosas por el bien de ustedes que caminan en tinieblas,
para que vean dónde están; y para que ustedes, altos cedros,
que ponen su confianza en el brazo de la carne,
dejen su jactancia y bajen del pináculo en el que están exaltados;
porque el mismo día de juicio tiene que venir sobre ustedes,
si es que alguna vez quieren conocer al Señor en verdad y justicia.
Ustedes deben pasar a través de la muerte de todas las cosas,
y ver la maldición cayendo sobre todo conocimiento y sabiduría que es de abajo; sí,
incluso experimentar la muerte de esa muerte que reina en ustedes,
la cual debe ser matada en la cruz de Cristo,
si es que alguna vez quieren llegar a la verdadera
paz y a experimentar la salvación eterna.

Por lo tanto, todos ustedes que adivinan y están llenos de imaginaciones,
que han inventado una fe y un Cristo y una salvación de su propia imaginación,
mientras que todavía viven en los deseos y contaminación del mundo,
y en las costumbres y modas que perecen; a ustedes les digo, sus expectativas perecerán,
y en dolor serán sepultados; porque donde sea que se experimente salvación,
allí también se experimentará la vida de Cristo;
pero ustedes quieren experimentar salvación mientras continúan
manifestando y viviendo en la vida del diablo.

Por lo tanto, sean advertidos, porque no son sus buenas palabras sin la vida de piedad,
ni sus discursos altivos lo que Dios acepta; porque Él solo acepta lo que es de Sí mismo,
y lo que es hecho en la criatura por Su propia voluntad y poder,
y esto que Él hace destruirá la voluntad y poder
de la carne junto con toda su justicia propia.
La obra que Él hace en el hombre--que Él mismo ejecuta,
por Su poder y en Su pacto--es perfecta y es aceptada por Él,
y por lo tanto ya no es la criatura sino Cristo, el cual es el todo en todos Sus Santos.
Así Él saca a todos los que lo siguen fuera de las obras de condenación,
que son realizadas en la naturaleza desobediente,
y están bajo maldición ya sea que el hombre esté orando o arando,
o cualquier cosa que haga mientras la naturaleza de Caín todavía viva,
la cual está desterrada del lugar de aceptación de Dios.
Y todos los que siguen a Aquel quien es la luz (que lleva a todo el que
cree en ella y la sigue a las obras vivas de justicia que son hechas por
medio de Cristo a través de la fe) son aceptados y complacen a Dios;
y aquí toda jactancia queda excluida, porque todo es de Él y por Él,
quien produce tanto el querer como el hacer,
y así el Señor es admirado en todas Sus obras, y Sus obras en verdad lo alaban.

Por lo tanto, les digo a todos los que buscan justicia y están cansados: Vengan ahora,
y les mostraré dónde podrán encontrar el verdadero descanso;
porque Él lo ha derramado en mi corazón libremente
por Su gracia y eterno amor hechos manifiestos,
después de una larga y oscura noche por la que pasé sin guía,
y por lo tanto caí en el pozo, y tropecé,
y entonces el dolor y la angustia me rodearon por todas partes.
Pero ahora Él ha derramado Su gracia en mi corazón, la cual salva de pecado,
y lleva fuera de las obras de condenación a Su morada, donde nada inmundo puede entrar.
Y es esta gracia la que me ha separado del pecado,
y me ha constreñido a negarme a mí mismo,
y a seguir al Señor a través de la muerte de la cruz y de negar todas las cosas,
tanto esposa e hijos, como casa y tierras, país y nación,
para proclamar Su nombre en el exterior en contra de mi propia voluntad,
y para dar a conocer a todos las riquezas de Su gracia,
la cual aquellos que esperan en la luz de Jesucristo llegarán a ver.

Así que vuelvan a su casa, a su propio corazón,
ustedes que han estado buscando al que vive entre los muertos, uniéndose a extraños,
sin encontrar nada sino una cáscara o sombra, y viviendo en un sueño. En verdad,
ustedes ahora están más lejos de lo que estaban antes,
por estar corriendo y buscando en su sabiduría y comprensión terrenal.
Ustedes solo han obtenido un informe de lo que Cristo dijo e hizo,
y de cómo los santos lo adoraban; pero mientras sus ojos han estado en lo externo,
no han encontrado a Aquel a quién todos los santos adoraban en espíritu,
y experimentaban como su salvación en el interior.
Por lo tanto, todo el que tenga sed, venga a Cristo Jesús el cual está cerca de todos.
Esperen conocer Su Palabra en su interior, la cual está en el corazón y en la boca,
porque la fe viene por ella,^
footnote:[Romanos 10:17]
a medida que ustedes diligentemente esperen y mantengan sus mentes vueltas a ella.
Esto es lo que les muestra el pecado y el mal en su interior,
y pone de manifiesto todo lo que han llevado a cabo contrario a ella, sí,
incluso todo cuanto han hecho.^
footnote:[Juan 4:29]
Esta Palabra escudriñará sus corazones,
porque ella es el ojo que descubre el engaño en todos sus disfraces,
y les dejará ver cómo ella a menudo los ha reprendido y llamado,
y cómo ustedes no han respondido a Su llamado, sino que han escogido sus propios caminos.
De este modo esa parte en ustedes que desea conocer a Dios no ha sido nutrida ni alimentada,
sino que ha estado pasando hambre mientras que otra parte
ha sido alimentada y ahora ha engordado para la matanza.

Ahora amigos, hay algo en el hombre que debe recibir a Cristo, algo que es de Él,
a lo cual Él viene (¡aprendan qué es esto!);
y Él solo puede unirse o estar unido con eso que es puro y sin mancha;
porque es el puro de corazón el que ve a Dios,
y no la mente carnal (que siempre desprecia Su gloria).
Él no se revela a esa mente que sale a cazar en el exterior, que es la de Esaú,
porque la bendición no es nada para él. Este es el profano,
el Judas que lo traiciona y lo vende por algo que no tiene valor; para los cerdos,
la perla no tiene ningún valor.
¡Oh lean espiritualmente!
Porque la semilla a la que le fue hecha la promesa es hollada y muere
de hambre en las plazas de la Sodoma y Egipto que están en sus corazones,
donde Cristo fue y es crucificado.^
footnote:[Apocalipsis 11:8; Hebreos 6:6]

Por lo tanto, ustedes que ven las tinieblas en las que yacen, vuelvan a casa,
y pongan su mente en ese Espíritu que es manso y humilde.
No sean apresurados ni precipitados,
más bien permanezcan firmes en quietud y mansedumbre,
para que puedan oír la voz suave y delicada,
que no podrán oír sin primero humillarse mucho internamente.
Porque las voces de los egipcios y encantadores, de Faraón y Herodes son fuertes y altas,
y ustedes cuyas mentes están divagando en el exterior
piensan que estas voces son la voz de Dios.
Pero yo les digo, estén quietos,
porque Aquel a quién ustedes deben oír (para que sus almas vivan) "`no gritará,
ni alzará Su voz, ni la hará oír en las calles.`"^
footnote:[Isaías 42:2]
Así que, si desean oírlo, sean humildes y estén quietos,
y esperen escuchar esa Palabra que separa lo precioso de lo vil.

Ahora la luz en la que deben esperar está cerca de ustedes, sí, está en ustedes.
Ella es el ojo que ve,
y el oído que escucha lo que es del Señor. Porque eso que es visible es natural y carnal,
y el oído natural no puede oír la palabra del Dios espiritual.
Ese oído que escucha externamente es sordo, y el ojo que mira hacia afuera es ciego.
Pero eso que revela al Dios puro y espiritual debe
estar en ustedes como algo puro y espiritual,
porque "`nadie conoce las cosas de Dios, sino el Espíritu de Dios.`"^
footnote:[1 Corintios 2:11]
¿No daba Su Espíritu testimonio a sus espíritus antiguamente?^
footnote:[Romanos 8:16]
¿Y no lo hace Él ahora en todos los que verdaderamente lo conocen?
Así pues, a medida que amen la luz, y mantengan sus mentes en lo interno,
sentirán el movimiento de Jesucristo en sus corazones; y a medida que la amen,
ella los sacará de todo pecado, y los santificará,
y les mostrará tanto el día de la venganza como el
año aceptable del Señor. Este es Cristo,
a quién el Padre ha dado por pacto^
footnote:[Isaías 42:6, 49:8]
para sacar al hombre de la separación y llevarlo a Sí mismo otra vez,
y para reconciliar al hombre consigo mismo mediante la sangre de la cruz.
El que es la luz _es_ el pacto; y el que es el pacto es la luz;
porque el pacto y la luz son una misma cosa en Él;
y este pacto de paz es ofrecido a ustedes que están lejos.
Este don es gratuito,
y es ofrecido libremente a todos los que están dispuestos a recibirlo;
y sin embargo ustedes no pueden recibir el don en sus propias voluntades,
sino solo a través de la negación de sus propias voluntades;
porque la luz siempre es contraria a la voluntad terrenal del hombre,
y a medida que reciben la voluntad de Dios, deben negar sus propias voluntades.
Así llegarán a hacer la voluntad de Otro, y Otro los guiará y conducirá,
y todo esto será una obra únicamente de Dios, no de ustedes mismos,
sino llevada a cabo por Cristo en Su propio camino y verdad.

De esta forma se establece el pacto de Dios con la Semilla, y el fundamento está firme,
y Su promesa es cumplida en ustedes, a medida que experimentan la semilla que es una,^
footnote:[Gálatas 3:16]
en quién se cumple la promesa.

Por lo tanto, amigos,
deben esperar de tal manera que el juicio se establezca dentro de ustedes,
porque este es Aquel que es el juez y la luz del mundo.
Así que esperen hasta que vean Su ley establecida en su interior,
que es añadida para derribar la transgresión, para destruir toda injusticia en ustedes,
y para someter a un yugo la naturaleza rebelde que
ha tenido su libertad en la parte terrenal,
y así llegará a decaer.
Porque la ley produce ira sobre el engaño en ustedes que ha tenido preeminencia,
y así experimentarán el trueno a medida que los sellos sean abiertos,
junto con terremotos y relámpagos.
Pero al permanecer aquí,
tanto el transgresor como la transgresión que son contrarios a la ley serán cortados.
Y cuando haya un tiempo de gran aflicción, angustia, prueba y tentación,
esperen con paciencia en el juicio, y dejen que el Señor complete Su obra en ustedes.
Y así, a medida que se vuelvan a Aquel que los ha azotado y herido,
serán vendados y sanados por Él mismo.
Pero entreguen todo a la gran matanza del Señor en la cruz,
todo lo que sea manifestado por la ley pura de Dios.
Y a medida que la tierra de sus corazones sea arada,
la semilla que ha sido sembrada brotará, las piedras serán quebradas,
las aguas serán derramadas, y así verán las promesas cumplidas,
las cuales fueron hechas a esa semilla que ahora sale de la tumba.
Así el amor de Dios aparecerá en sus corazones, y ustedes serán afirmados,
y hallarán esperanza en medio de la calamidad.

Entonces a medida que el pecado sea crucificado en ustedes,
y pierda su dominio sobre ustedes, verán a Aquel que ha nacido bajo la ley,
quien cumplió la ley,
y quien ahora la cumple en todos los que andan conforme a Él en el Espíritu,
y ya no satisfacen los deseos de la carne.
Y a medida que se mantengan en sus mentes vueltos a la luz, verán el ministerio de Juan,
el agua que lava, y cómo este prepara el camino, y vuelve el corazón a Dios,
"`no sea que Él venga y hiera la tierra con maldición;`"^
footnote:[Malaquías 4:6]
porque su ministerio quebranta las montañas, las remueve, y allana el camino.
Y a medida que sus mentes continúen vueltas al Señor,
y obedezcan el don de Cristo que les ha sido dado,
experimentarán el verdadero arrepentimiento para vida,
y encontrarán algo levantándose y resplandeciendo en ustedes, y abriendo sus corazones,
el cual anhela al Señor y Su justicia.
Y al permanecer en obediencia bajo la cruz, el velo será rasgado,
y ustedes verán a Aquel que los ha apartado del pecado mediante
Su don de gracia hecho manifiesto en sus corazones.

Por lo tanto, esperen con paciencia, y manténganse en la semilla de vida,
y cosas ocultas se revelarán en ustedes, incluso los misteriosos dichos de antaño;
y Aquel que le habló en parábolas a la semilla de la serpiente,
revelará el significado de las parábolas a Su propia semilla.
Y entonces verán a Aquel que han traspasado, a saber,
al Cordero que ha sido inmolado desde la fundación del mundo,
y sus corazones serán quebrantados.
Pero para los que permanecen fieles en su medida, Su amor se incrementará en sus almas,
y Su don bueno y perfecto se les manifestará,
y llegarán a sentir esa esperanza que es como un ancla para el alma,
y que purifica el corazón. Y a medida que permanezcan en la perfecta
ley de libertad que es revelada en ustedes por el Espíritu,
el opresor será cortado, y todo será encadenado,
y el espíritu inmundo será atado y encerrado en densas tinieblas para siempre.
Y así serán redimidos de la esclavitud de pecado,
y levantados por encima de las prisiones de la muerte,
en la semilla pura que vive en ustedes,
y su deleite estará en hacer la voluntad del Padre,
que los ha redimido del pecado y de su ley, para que vivan en la justicia y su ley.

Pero todos ustedes que tienen hambre y sed de justicia,
deben esperar en eso que siente la sed,
para que puedan recibir el don que los limpia y los purifica de toda injusticia.
Y conforme este don se revele en ustedes, y ustedes lo obedezcan,
los llevará a la verdadera paz,
al revelar en sus almas la semilla inmortal que no viene por la voluntad del hombre,
sino que es contraria a ella.
Este es el Hijo de Dios el cual es antes de todo tiempo,
guía fuera del tiempo y a quien el Padre reveló en Pablo.
Y este es Aquel de quien yo fui hecho testigo,
y en quién tengo redención por la sangre de la cruz,
el cual vino para hacer la voluntad de Su Padre,
y todavía la hace en este día dondequiera que Él sea experimentado.

Así que guarden silencio todos ustedes predicadores,
que creen con una fe y enseñan una fe,
mediante la cual nadie puede ser limpiado de pecado mientras esté en la tierra.
Ustedes y su fe son desaprobados,
porque esa fe no es la misma fe "`que ha sido una vez dada a los santos,`"^
footnote:[Judas 1:3]
que daba victoria sobre el mundo,
y por medio de la cual los antiguos creyentes obtuvieron la victoria.
Su predicación es vana, su esperanza y fe son vanas,
y siguen escuchando en vano mientras el don perfecto
de Dios no sea experimentado en el interior;
porque es la Palabra de vida la que "`hace perfectos para siempre a los santificados,`"^
footnote:[Hebreos 10:14]
y la que puede "`hacer perfectos a los que se acercan,`"^
footnote:[Hebreos 10:1]
y la que presenta delante de Él a todos los que creen "`sin mancha, ni arruga,
ni cosa semejante.`"^
footnote:[Efesios 5:27]

¿Por qué se han elevado tan alto en palabras,
cuando son exactamente los mismos que eran antes, si es que no son peores?
No piensen que esta es una palabra dura, porque saben que es así con muchos de ustedes.
Ustedes son pesados en la balanza de la luz que es pura,
y sus propias palabras los traicionan, y manifiestan que ustedes no son lo que profesan;
porque cuando son probados por las prácticas de los santos,
por la vida que estaba en ellos, y por el disfrute que ellos tenían de Dios,
ustedes son hallados tan lejos de ser como ellos que incluso se oponen a la fe
que ellos tenían. Y así ustedes han imaginado una fe y una justicia propias,
y un Cristo del que hablar, y una redención que les permite vivir en sus deseos,
y complacer a los hombres en las costumbres y modas del mundo,
contendiendo por el pecado,
y dejando la posibilidad de alcanzar la justicia perfecta para otro mundo.
Así el diablo los ha engañado, y los ha enseñado a hacer cubiertas,
pero estas no los esconderán en el día de Su aparición;
porque Dios no se une a eso que es imperfecto,
ni la verdadera fe echa mano de una injusticia imperfecta.
No, los santos nunca profesaron una fe como esta.
Porque ellos recibieron la fe como el don de Dios,
y la medida más pequeña de ella era perfecta,
y a medida que permanecían en ella (aunque apenas era como
un grano de mostaza) veían que los montes eran quitados.
Sí, su fe echaba mano de la justicia de Cristo, la cual era y es perfecta, sin manchas,
ni arrugas, ni cosa semejante; y Su justicia se manifestaba en ellos por fe,
y por ella ellos eran justificados ante los ojos de Dios.

¡Oh! ¿cuándo se cansarán de alimentarse del viento, y de las algarrobas entre los cerdos?
¿Cuándo inquirirán y buscarán al Dios vivo que es poder?
¿Cuántos años han hablado de Su poder por venir?
Pero siguen estando muy lejos, si no es que más lejos de lo que estaban antes.
¿Cuánto tiempo han hablado de la gloria que será revelada,
de Su ley que será escrita en el corazón, de que Dios enseñará a Su pueblo Él mismo,
y de Su Espíritu que será derramado sobre hijos e hijas,
y no pueden ver que todavía no han obtenido nada de esto?
Uno que está hambriento viene a ustedes,
y ustedes que están llenos lo alimentan con los viejos sedimentos que han establecido,
la vieja levadura de nociones y conceptos vacíos, el vino de uvas amargas.
Y si alguno testifica y experimenta en su vida las
cosas de las que ustedes hablan con palabras,
entonces ustedes no quieren reconocer su testimonio.
Y cuando uno les declara qué es el poder de Dios,
y dónde se debe esperarlo y experimentarlo,
ustedes dicen que eso es algo demasiado débil y pequeño,
y que un día el poder vendrá como ustedes lo han prescrito.
¿Cuánto tiempo han hablado del Espíritu y de adorar en el Espíritu?
Y sin embargo niegan Su guía y enseñanza, viven en el régimen viejo de la letra,
y establecen una adoración que es carnal y visible.

Ahora bien,
el Espíritu de Dios es un poder operativo que obra un cambio en el fundamento mismo,
y traslada a todos los que lo siguen y obedecen a Su propia naturaleza;
pero todas esas cosas sobre las que ustedes contienden tanto, son solo la sombra.
Porque la Palabra era en el principio y daba vida.
Ella es espiritual, y cuando es conocida y experimentada en el interior del corazón,
separa de la muerte y le da vida a todo el que cree en ella.
¿Qué Cristo es este que ustedes predican?
¿Qué evangelio es este,
que no salva verdaderamente tanto del pecado y como de la condenación?
Porque donde la Palabra del verdadero Cristo es experimentada,
lo primero que hace es condenar el pecado, luego lo limpia y remueve, lo borra,
destruye la raíz de la que fluye, y hace una nueva creación en justicia.
Sin embargo, ustedes dicen, "`Él ha quitado nuestros pecados.`"
¿Cuánto de su pecado Él ha quitado?
Si dicen "`todos,`" entonces ¿por qué sus conciencias siguen perturbándolos con culpa?
Pero si dicen, "`Todo está hecho en Cristo,`" entonces pregunto, ¿dónde está hecho,
si el pecado todavía no ha sido removido de sus corazones?
¿Tienen Su testimonio dentro de ustedes?
De cierto les digo, que mientras el testimonio de Jesús testifique ahora contra ustedes,
Él no testificará al mismo tiempo a favor de ustedes.
Pero luego de que han creído en Cristo (como dicen) y han recibido todas Sus ordenanzas,
si algo en su corazón los juzga y les causa tribulación,
ustedes lo llaman "`una tentación,`" y así ponen la luz por tinieblas,
y las tinieblas por luz.
Pero yo les digo, no hay culpa donde el pecado es quitado y crucificado,
sino paz y descanso en el Dios santo, que es inmutable.
Pero entonces ustedes dicen, "`Si debemos cumplir la ley, entonces ¿de qué sirve Cristo?`"
Respondo, Aquel que permanece para siempre cumplió la ley,
y también la cumple en todos los que lo conocen y experimentan Su obra;
y en esto el hombre llega a ser justificado ante los ojos de Dios por medio de Cristo,
el cual hace todas nuestras obras en nosotros y por nosotros; y así el yo llega a morir,
y "`porque Él vive, nosotros también vivimos.`"^
footnote:[Juan 14:19]
Gloria a Dios por siempre.

¡Oh! ¿cuándo buscarán sabiduría y oirán para que sus almas vivan?
¿Por cuánto tiempo más confiarán en las imaginaciones de sus propios corazones?
De cierto les digo, está llegando el tiempo cuando sus edificios caerán,
y no quedará piedra sobre piedra, que no sea derribada.
El dolor se apresura a alcanzarlos, porque ustedes no quieren tomar la cruz de Cristo,
ni recibir la Palabra de vida que los apartaría de toda injusticia,
y del mundo y su naturaleza, sino al contrario han endurecido sus corazones,
entesado sus arcos y lanzado sus saetas contra el Señor y Sus ungidos.

[.asterism]
'''

Después de haber recibido la verdad a través del ministerio de George Fox,
y de haber experimentado una transformación hecha en su corazón por el poder de Dios,
Francis Howgill siguió adelante hasta convertirse
en un eminente ministro en la Sociedad de Amigos,
predicando a Cristo de gracia, como lo había recibido de gracia.
En 1652,
él y su frecuente compañero Edward Burrough viajaron
a Bristol y a varios lugares de la nación,
sufriendo el encarcelamiento ese año en una celda
asquerosa y hedionda en la cárcel de Appleby.
Cuando fueron puestos en libertad al final del año,
se volvió incluso más valiente y audaz por el nombre del Señor,
y viajó a pie por toda la nación predicando a multitudes
y dirigiendo a todos a Cristo Jesús su maestro y Salvador.
En la primavera del año 1654 él fue a Londres en compañía de Edward Burrough,
donde se dice que ellos fueron los primeros que predicaron
públicamente las doctrinas de los Amigos en esa gran ciudad.
Se dedicó mucho tiempo y esfuerzo a la sociedad que crecía rápidamente
en Londres y alrededores por los siguientes años,
aunque él hizo viajes ministeriales a otros lugares en Inglaterra,
y también pasó seis meses en Irlanda predicando la
verdad y volviendo los corazones de muchos a Dios.
En 1661,
él y muchos otros fueron encarcelados en Londres bajo la sospecha de que los Amigos
estaban involucrados en la insurrección de la Quinta Monarquía que se levantó con armas
contra el gobierno del Rey Charles II que había sido establecido recientemente.
Pero no teniendo nada que ver con esos sangrientos hechos,
fue puesto en libertad y continuó trabajando en la obra del Señor hasta el año 1663.

En algún momento cerca del comienzo de este año, fue apresado en un mercado en Kendal,
en Westmoreland, dónde estaba ocupado en su negocio habitual.
Al ser convocado por el alguacil principal a comparecer ante los jueces de paz,
le leyeron el juramento de lealtad y supremacía; y debido a que, por causa de conciencia,
en obediencia a los mandamientos de Cristo, él no podía jurar,
ellos lo enviaron de nuevo a la cárcel de Appleby,
donde lo mantuvieron en un agujero lleno de humo por cinco
meses hasta el tiempo de la audiencia del tribunal.

Como a miles de otros antiguos Amigos,
Howgill fue acusado y sentenciado por negarse a jurar,
y por continuar reuniéndose con otros a adorar al Señor en congregaciones
que no eran aprobadas por la Iglesia de Inglaterra.
Al entrar en la corte, y afirmar que él no tenía nada de qué acusarse,
porque su conciencia le daba testimonio de que amaba la paz,
y la procuraba con todos los hombres, el siguiente intercambio de palabras tuvo lugar:

[.discourse-part]
__Juez:__ ¿Por qué en lugar de ir a la iglesia se reúnen en casas y en conventículos^
footnote:[Una junta ilícita y clandestina.]
privados, que la ley prohíbe?

[.discourse-part]
__Francis Howgill:__ Nos reunimos solo para adorar al verdadero Dios en espíritu y verdad,
teniendo a los cristianos primitivos como nuestro ejemplo;
y con ningún otro fin más que ser edificados y glorificar a Dios;
y donde están dos o tres congregados en el nombre de Cristo, y Él está en medio de ellos,
allí hay una iglesia.

[.discourse-part]
__Juez:__ Eso es verdad;
pero ¿cuánto tiempo ha pasado desde la última vez que has ido a la iglesia;
o estás dispuesto a ir a la iglesia que la ley permite?
Dame algunas razones por las que no asistes.

[.discourse-part]
__Francis Howgill:__ Tengo muchas para darte si tienes paciencia para oírme: primero,
Dios no mora en templos hechos con manos de hombres: segundo,
la casa parroquial ha sido un templo para ídolos, es decir, para ceremonias e imágenes;
y no me atrevo a tener comunión con ídolos, ni adorar en templos de ídolos; ¿porque,
qué tenemos nosotros que ver con los ídolos, y con sus templos y adoración?

[.discourse-part]
__Juez:__ ¿No habían casas en las Escrituras llamabas las casas de Dios, y templos?

[.discourse-part]
__Francis Howgill:__ Sí, bajo la ley;
pero los cristianos que creyeron en Cristo se apartaron de estas casas y templos,
y de los templos de los gentiles también, y se reunían en casas,
y partían el pan de casa en casa; y la Iglesia no estaba confinada a un lugar particular,
ni lo está ahora.

[.offset]
+++[+++El juez interrumpió]

[.discourse-part]
__Juez:__ ¿Responderás a tu acusación?

[.discourse-part]
__Francis Howgill:__ No sé cuál es.
Nunca la he oído, aunque a menudo he deseado una copia.

[.discourse-part]
__Juez:__ Secretario, léala.

[.offset]
+++[+++Entonces la leyó, declarando que "`Francis Howgill de manera rebelde,
obstinada y con menosprecio se negó a jurar cuando se le leyó el juramento.]

[.discourse-part]
__Francis Howgill:__ Lo niego.

[.discourse-part]
__Juez:__ ¿Qué niegas?

[.discourse-part]
__Francis Howgill:__ La acusación.

[.discourse-part]
__Juez:__ ¿No te negaste a jurar?
Y la acusación te declara culpable de no haber jurado.

[.discourse-part]
__Francis Howgill:__ Primero,
le declaré al tribunal que estaba de acuerdo con la sustancia del juramento,
como todos ustedes saben, y les ofrecí ponerlo por escrito.
Segundo, les dije que no me negaba a jurar por obstinación o rebeldía,
ni en menosprecio a la ley o gobierno del rey;
porque yo más bien escogería mi libertad que las cadenas;
y soy consciente de que es probable que esto me cause un gran daño. Tengo esposa e hijos,
y algunos bienes, con los que podríamos subsistir, y hacer bien a otros;
y sé que todo esto está en riesgo; pero si mi vida también lo estuviera,
aún así no me atrevería a hacer otra cosa, no sea que incurra en el desagrado de Dios.
¿Ustedes creen que yo perdería mi libertad voluntariamente,
y sufriría el despojo de mis bienes, y la ruina de mi esposa e hijos,
por obstinación y rebeldía? Seguro que no.

[.discourse-part]
__Juez:__ Jurado, ustedes ven que él niega el juramento,
y no se declarará culpable de la acusación,
sino que solo objeta contra ella por la forma en que está escrita.
Pero ustedes ven que él no jurará, y sin embargo él dice que niega la acusación,
y ya ven en qué motivos se basa.

[.offset]
+++[+++Entonces el jurado dio un veredicto de culpabilidad,
y la corte se disolvió por el día. Al siguiente día, hacia la tarde,
cuando habían procesado a todos los presos,
Francis fue llevado al tribunal para recibir su sentencia.]

[.discourse-part]
__Juez:__ Ven ahora, la acusación ha sido probada en tú contra,
¿qué tienes que decir para explicar por qué no debe emitirse la sentencia?

[.discourse-part]
__Francis Howgill:__ Tengo muchas cosas que decir, si ustedes están dispuestos a escucharlas.
__Primero,__ como había dicho, no me negué a jurar por obstinación o rebeldía; __segundo,__
porque jurar es algo directamente contrario al mandamiento de Cristo.
__Tercero,__ porque también es contrario a la doctrina de los apóstoles.
__Cuarto,__
incluso contrario a algunos de los principales pilares de la iglesia de Inglaterra;
como por ejemplo, el obispo Usher, que fue arzobispo de Irlanda por un tiempo,
dijo en sus obras que los Waldenses negaban todo tipo de juramento en
su época debido a ese mandamiento de Cristo y del apóstol Santiago,
y que esto era motivo suficiente; y Dr. Gauden, difunto obispo de Exeter,
en un libro de él que leí recientemente,
citó muchos padres antiguos para demostrar que por los primeros tres siglos,
los cristianos no juraban, así que esta no es una doctrina nueva.

[.discourse-part]
__Juez:__ ¡Sin duda estás equivocado!

[.discourse-part]
__Francis Howgill:__ No tengo el libro aquí.

[.discourse-part]
__Juez:__ ¿Dirás tú con honestidad que ellos negaban todo tipo de juramentos?

[.discourse-part]
__Francis Howgill:__ Lo que he dicho es verdad.

[.discourse-part]
__Juez:__ Pero ¿por qué no vas a la iglesia y escuchas el servicio, y te sometes a la ley,
y obedeces toda institución humana por causa del Señor?

[.discourse-part]
__Francis Howgill:__ Nosotros estamos sujetos, y por esa razón pagamos impuestos, tributos,
y derechos de aduana, y le damos al César lo que es del César,
y a Dios lo que es de Dios, a saber, adoración, honor y obediencia;
y si te refieres a la congregación parroquial, te digo sinceramente, estoy persuadido,
sobre un buen fundamento, que sus maestros no son los ministros de Cristo,
ni es su adoración la adoración de Dios.

[.discourse-part]
__Juez:__ Por algunas cosas pequeñas en el servicio, ¿lo rechazas todo?

[.discourse-part]
__Francis Howgill:__ Primero, es evidente que ellos son servidores del tiempo,^
footnote:[Un servidor del tiempo es el que adapta sus opiniones y prácticas a los tiempos,
o al cambio de los poderes gobernantes.]
porque por un tiempo predican como '`servicio divino,`'
lo que en otro momento habían tachado como papista,
supersticioso e idólatra.
Y eso que han predicado por veinte años, lo abandonan todo en un día;
y entonces luego quieren llamarlo divino otra vez,
y obligar a todos a creer lo que ellos mismos una vez desecharon.

[.discourse-part]
__Juez:__ ¿Qué, desde que llegó el rey?

[.discourse-part]
__Francis Howgill:__ Sí,
los mismos hombres que predicaron contra algo antes de que viniera el rey,
ahora lo recomiendan y obligan a todos a creerlo.
Son tan inestables y fluctuantes,
que no podemos creer que ellos sean los ministros de Cristo.
__Segundo,__ enseñan por precio, y viven por un mantenimiento forzado,
y quieren imponer una fe sobre los hombres,
en contra de la regla de Cristo y sus apóstoles,
que dijeron que cada uno esté plenamente convencido en su propia mente, y,
"`todo lo que no proviene de fe, es pecado.`"
Y aunque los sacerdotes dicen que la "`fe es el don
de Dios,`" aun así quieren imponer su fe sobre nosotros;
y debido a que no podemos recibirla, ellos claman,
"`ustedes no están sujetos a la autoridad ni a las
leyes,`" y solo amenazan con despojo de bienes,
prisiones y destierros.
Podría mencionar más detalles.

[.offset]
+++[+++Entonces el juez interrumpió]

[.discourse-part]
__Juez:__ Bueno, veo que no jurarás, ni te conformarás, ni te sujetarás,
y piensas que te tratamos con severidad;
pero si te sujetaras a las leyes no tendríamos necesidad.

[.discourse-part]
__Francis Howgill:__
Yo en verdad juzgo que ustedes nos tratan con severidad
por nuestra obediencia a los mandamientos de Cristo.
Y aunque no envidio la libertad de ningún hombre,
les pregunto ¿pueden mostrarme cómo alguna de esas
personas por las que este acto fue hecho,
ha sido procesada por este estatuto?

[.discourse-part]
__Juez:__
¡Oh sí! Puedo mencionarte muchas personas de todas partes
del país que han sido procesados con el estatuto __premunire.__
Yo mismo lo he hecho, y he pronunciado la sentencia contra varios.

[.discourse-part]
__Francis Howgill:__ ¿qué, contra papistas?

[.discourse-part]
__Juez:__ No.

[.discourse-part]
__Francis Howgill:__ ¿Qué, contra cuáqueros?
Así lo he escuchado en verdad.
Entonces, aunque el estatuto fue hecho contra papistas,
aún así los dejan a ellos tranquilos y lo ejecutan contra los cuáqueros.

[.discourse-part]
__Juez:__ Bueno, ustedes se reúnen en gran número, y crecen.
Pero hay un nuevo estatuto que los reducirá.

[.discourse-part]
__Francis Howgill:__ Bueno, si tenemos que sufrir, es por amor a Cristo y por hacer el bien.

[.offset]
Entonces Francis estando en silencio, el juez pronunció la siguiente sentencia:
"`Quedas fuera de la protección del rey, y de los beneficios de la ley;
tus tierras son confiscadas al rey durante tu vida,
y tus bienes y pertenencias para siempre;
y tú permanecerás prisionero el resto de tu vida.`"

[.discourse-part]
__Francis Howgill:__ Una dura sentencia por mi obediencia a los mandamientos de Cristo.
El Señor los perdone a todos.

[.discourse-part]
__Entonces el juez se levantó y dijo:__ Bueno,
si todavía estás dispuesto a sujetarte a las leyes, el rey te mostrará misericordia.

[.discourse-part]
__Francis Howgill:__ El Señor me ha mostrado misericordia;
y yo no he hecho nada contra el rey, ni contra el gobierno, ni contra ningún hombre,
bendito sea el Señor, y en esto consiste mi paz;
porque es por causa de Cristo que padezco, y no por hacer el mal.

[.small-break]
'''

Francis Howgill soportó su encarcelamiento con gran paciencia,
y demostró tanta mansedumbre, entrega y amor,
que se ganó el amor y la estima de toda la familia del carcelero,
y de muchos otros en la ciudad de Appleby.
Y tan grande era la confianza que las personas ponían en él,
que mientras estaba en prisión,
frecuentemente le remitían a él sus diferencias para que las resolviera justamente.

Hallamos que él continuaba dedicado diligentemente a promover
la causa de la Verdad y la justicia mientras era prisionero,
escribiendo epístolas a aquellos con quienes estaba unido en comunión religiosa,
y respondiendo a las publicaciones de algunos que
tergiversaban los principios de los Amigos.
También escribió varias epístolas y escritos doctrinales,
de los cuales el más conocido es su tratado titulado [.book-title]#Algunos
de los Misterios del Reino de Dios Declarados#.

La paz interna con la que él fue bendecido,
al someterse pacientemente a la pérdida de su libertad por mantener fielmente esos testimonios
que creía firmemente que el Señor requería que él abrazara y defendiera,
es increíblemente demostrada en las siguientes palabras, añadidas a una de sus epístolas:
"`Desde la cárcel de Appleby, el lugar de mi descanso,
donde mis días y horas me son placenteros.`"

Cuando alguien mencionaba la gran cantidad de tiempo que él había sido prisionero,
Francis diría: "`Que la voluntad del Señor sea hecha.`"
Él se enfermó el 11 del onceavo mes de 1668; y poco tiempo antes de esto,
distribuyó sus bienes, y puso su casa en orden,
estando consciente del desgaste de su "`hombre exterior.`"
Su amor por sus hermanos y compañeros en la obra era muy grande;
y como testimonio de ello, les dejó algo a varios de ellos a modo de recuerdo;
también tenía en cuenta a la Iglesia,
y dejó un patrimonio para que fuera distribuido entre todos los pobres de la familia
de la fe en los lugares donde vivía. Dos años antes de su muerte en la cárcel de Appleby,
escribió la siguiente carta a su pequeña hija Abigail.

[.embedded-content-document.letter]
--

[.salutation]
Hija Abigail,

Esto es para que lo observes, lo guardes y le prestes atención todos los días de tu vida,
para que regule tu vida y tu conducta en este mundo;
para que tu vida sea feliz y tu fin bendito,
y para que Dios pueda ser glorificado por ti en tu generación. Estas cosas
te las entrego y te las aconsejo para que las guardes siempre,
siendo que son las cosas más importantes y las únicas que tengo para ofrecerte,
las cuales estimo más que las riquezas externas.
Ojalá que tú también las estimes así, y observes y guardes mis dichos;
te encarezco delante de Dios, y por la venida de nuestro Señor Jesucristo,
que observes lo que te digo.
Estoy movido por el Señor a dejarte esto a ti, en tierno amor y afecto hacia ti, mi hija,
para que el Señor te dé Su bendición,
y haga prósperos tus caminos y que tu postrimería sea paz.

Ante todo, conoce esto: Yo no nací en grandes posesiones,
ni heredé grandes cosas en este mundo;
pero el Señor siempre me ha provisto de lo necesario y suficiente,
y ha sido como un Padre tierno para mí,
porque mi corazón ha confiado en Él y amado los caminos de justicia desde
niño. No tengo una gran porción de las cosas de este mundo para darte;
sin embargo, de lo poco que tengo, con lo que Dios me ha bendecido,
te daré algo que no mencionaré aquí, pero lo sabrás a mi muerte.
No obstante, te encomiendo a tu querida madre, quien, confío,
proveerá lo suficiente para ti;
para quien mi corazón ha sido recto delante del Señor. Cuando me casé con tu madre,
ella tenía una porción y una dote suficientes, que no deseo disminuir ni menoscabar;
y todo lo que era de ella (si le place al Señor que
yo muera antes que ella) se lo dejo libremente,
como fue siempre mi intención y propósito, lo cual no ha cambiado ni cambiará,
por la fuerza de Dios--como sólo Dios conoce y me da testimonio.
Esto será manifestado a todos en su debido tiempo,
como ya se ha manifestado delante del Señor,
quien ha estado conmigo en medio de muchas dificultades, pruebas y sufrimientos,
y ha levantado mi cabeza sobre mis adversarios, porque he confiado sólo en Su Nombre;
el cual en todo momento lo he encontrado ser un refugio,
y un pronto auxilio en tiempos de necesidad, y así será para ti,
si temes Su Nombre y confías en Él siempre.

Y ahora, querida niña, escucha las palabras de mi boca y atiende mi consejo.
Reflexiona en estas cosas que te dejo para que las observes,
a fin de que tus días se prolonguen sobre la tierra, y sean bendecidos y cómodos para ti,
y un honor para Dios en tu generación.

Tú naciste y viniste al mundo en un tiempo de profunda
prueba y dificultad para mí--no del Señor,
quien siempre me ha hablado paz y me ha sostenido--sino
por causa del adversario de la humanidad,
quien siempre busca devorar lo bueno en todos,
y es el sembrador de discordia y maldad en los corazones de los que no le temen al Señor,
ni permanecen en Su consejo.
Él entra en estos, según se le da lugar para sus tentaciones, y ahí corrompe la mente.
Pero aunque entonces había una gran prueba sobre mí,
el Señor guardó mi corazón en rectitud hacia Él y me dio mucha paciencia.
Y aunque la tierra había sido quitada y echada al mar,
y todas las cosas externas habían sido confundidas,
y la naturaleza había cambiado su curso, con todo,
el Señor me dio la resolución y la fuerza para no angustiarme ni ofenderme,
porque Él me sostenía. En ese tiempo naciste tú, y por eso te llamé Abigail,
que significa "`gozo o deleite del padre;`" porque en ti
fui consolado y mi angustia presente fue mitigada.

Ahora, mi consejo para ti es que te acuerdes de tu Creador en los días de tu juventud,
y le temas al Señor en tu juventud,
y aprendas a conocerlo y a servirle todos tus días.
Busca primero el reino de Dios y su justicia.
Su reino no está lejos de ti; está dentro de ti.
Este consiste en vida y poder, y permanece en la justicia, verdad, equidad, juicio,
misericordia, longanimidad, paciencia, amor, luz y santidad;
siendo estas cosas su esencia y centro.
Por tanto, no busques el "`helo aquí`" o el "`helo allí`" fuera de ti,
en esta o aquella advertencia externa; porque muchos buscan ahí y nunca lo encuentran.
Pero busca, y hallarás; espera, y recibirás.

Si preguntas,
"`en qué debo buscar,`" o "`en qué debo esperar,`" y "`cómo debo buscar,`" te informo:
Debes silenciar todos tus propios pensamientos,
y debes volver tu mente a ese don que es puro, santo y bueno dentro de ti.
Busca y espera en eso, en la Luz de Jesucristo con la que has sido alumbrada,
la cual te muestra cuando haces mal, te refrena y te reprende.
Préstale atención a eso, y te mostrará las inclinaciones y pensamientos malvados;
y en la medida que lo ames,
verás como eso también someterá estas cosas y te
preservará fuera del mal para el tiempo por venir.

Porque aunque tú hayas nacido en el mundo como una criatura racional,
aun así debes nacer de nuevo y ser hecha una _nueva_ criatura, de lo contrario,
no podrás entrar en el reino de Dios.
Debes conocer a la Semilla del reino en ti misma (de la
que debes nacer) y ser formada de nuevo a la imagen de Dios.
Te he dicho que Dios la ha sembrado en ti--un grano de ella, una medida de ella,
una porción de ella, una medida de Luz y Verdad, de justicia y santidad.
Mantente vuelta a ella en tu mente; ámala y sentirás al Padre Celestial obrando en ti,
y creándote de nuevo para vida por medio de Jesucristo, quien te ha alumbrado.
Y sentirás el poder del Señor fortaleciéndote en tu poquito,
y haciéndote crecer en la Semilla inmortal de Su reino, y dejar atrás y superar todo mal,
para que mueras diariamente al mal y no tengas placer en él, sino en el Señor,
y en Su bondad y virtud derramadas en tu corazón,
lo cual gustarás y sentirás en el interior, y tendrás gozo y consuelo en ello.

Ama al Señor con tu corazón y con tu alma, es decir,
Al que te hizo y te dio (y a todas las otras cosas en el cielo y en la tierra) un ser.
Espera el conocimiento de Él en ti misma; Él no está lejos de ti,
sino cerca de ti y de todos los de corazón limpio lo invocan.
Pregunta a tu querida madre y ella te informará; ella lo conoce a Él,
y conoce el camino de vida y paz; por tanto, escucha su instrucción.

Dios es Espíritu, es un Espíritu puro de luz, vida y poder.
Él es el que escudriña el corazón y te muestra cuando haces mal, o piensas mal,
o hablas mal; y les muestra a los hombres y a las mujeres sus pensamientos.
Eso que muestra el mal, es bueno; y eso que muestra la mentira, es Verdad.
Esto está en tu interior;
préstale atención. En las Escrituras se le llama Espíritu de Dios; cree en Él, ámalo,
y Él vivificará tu corazón para el bien y someterá el mal.
Él es tu maestro cercano; ámalo.
Si actúas contrario a Él, te condenará; por tanto,
préstale atención a este Espíritu de Verdad y Él te alumbrará y te avivará.
Él abrirá tu entendimiento y te dará a conocer qué es Dios,
y a hacer lo que es bueno y aceptable ante Sus ojos.
Este Espíritu nunca se equivoca, sino que saca de todo error e introduce en toda verdad.

¡Oh, Abigail, cree mis palabras!
Ellas son las palabras de Dios y de la Verdad.
No seas descuidada, sino de mente sobria en tu juventud.
Espera en el Señor en el interior y escúchalo.
Dios es Luz inmortal, Vida inmortal, Verdad inmortal; un Espíritu perpetuo y eterno.
Él habla espiritual e invisiblemente dentro de los
corazones y consciencias de hombres y mujeres.
Escucha lo que Él dice y obedece Su voz, y tu alma vivirá. Teme ofenderlo,
o pecar contra Él; porque la paga del pecado es muerte.
Por tanto, aprecia Su amor en tu juventud y en tus años tiernos.

Lee las Escrituras y los libros de los Amigos,
y presta atención a lo que lees para obedecerlo, hasta donde entiendas.
Ora con frecuencia al Señor y pídele que te dé Su conocimiento
y abra tu entendimiento en las cosas de Su reino.
Escudriña tu corazón a menudo con la Luz de Cristo en ti;
manifiesta y lleva tus obras a la Luz, para que puedan ser probadas.
Examínate a ti misma, para ver cómo está el caso entre el Señor y tú;
y si ves que estás equivocada, humíllate y arrepiéntete.
Vuélvete a Él, y Él te mostrará misericordia; y luego ten cuidado en el tiempo por venir,
para que no corras al mismo mal de nuevo.
Mantén tu corazón limpio; vigila contra el mal en ti en esa luz que lo muestra;
en ella hay poder y por medio de ella tienes poder para vencer todo mal.

Querida hija, no te ocupes de los placeres del pecado que sólo duran un momento,
y su fin es miseria; más bien oponte a ellos y mantén sometida tu voluntad y afectos.
Así tu mente no tendrá placer en el mal, sino sólo en el bien;
y sentirás a la Semilla inmortal brotando en ti,
a La que le pertenecen la paz y el amor de Dios.

¡Oh, Abigail, estas cosas son grandes y de peso, y no deben ser menospreciadas!
Acompáñate siempre con los que le temen al Señor,
que le temen y lo adoran en espíritu y verdad, y llevan una vida santa e irreprochable.
No los niegues, sino ámalos y sufre con ellos.
Mira que no sigas a los maestros asalariados,
que predican para obtener ganancias y riquezas, y no permanecen en la doctrina de Cristo.
No les creas, no les prestes atención, porque no le hacen bien a la gente;
pero tú los verás por ti misma.
Estos a veces tienen una apariencia externa de piedad,
pero niegan el poder de Dios y la verdadera santidad.
Recuerda que te lo he dicho, como alguien que ha tenido un conocimiento perfecto de ellos.

Asegúrate de no dejar que nada separe tu amor de Dios ni de Su pueblo.
Aquellos que guardan Su ley, obedecen la voz de Cristo y llevan una vida santa,
son Su pueblo.
Estos siempre han sido odiados, rechazados y perseguidos,
y la gente mala y libertina siempre ha hablado mal de ellos.
Estos son el pueblo de Dios y Su amor, paz y bendición están con ellos.
Por tanto, crece entre ellos como una rama natural de la Vid viva,
y continúa todos tus días en obediencia a la voluntad de Dios.
Así sentirás gozo y amor en tu corazón,
lo cual debes perseguir por encima de todas las cosas,
y alcanzarás y obtendrás la paz eterna.
¡Qué el Señor te conceda esto, según las riquezas de Su misericordia y amor,
que perduran por los siglos de los siglos, amén!

Y ahora Abigail, con respecto a tu bienestar en esta vida,
este es mi consejo y recomendación para ti: Ama a tu querida madre,
obedécela y hónrala siempre.
Mira que no la aflijas, ni seas terca ni voluntariosa, sino sométete a ella,
y sé una hija obediente para ella;
porque su amor y cuidado han sido grandes sobre ti y tus hermanas,
lo que ha traído mucha preocupación sobre ella.
Aprende en tu juventud a leer y a escribir un poco, a coser y tejer,
y todos los elementos de buena labor que corresponden a una criada;
y huye de toda ociosidad y pereza que alimentan el pecado.
A medida que crezcas en años, guárdate del orgullo, la extravagancia y la curiosidad;
y más bien, conténtate con la ropa que tu madre te permita,
en lo que también puedes ser un buen ejemplo para otros.
No seas imprudente, desenfrenada, ni liviana, sino templada, moderada y casta;
y no te adelantes en palabras o expresión, sino sé rápida para oír y lenta para hablar.
Vive siempre con tu madre,
sé una ayuda para ella y cuídala en su vejez y en sus últimos años,
para que ella se consuele en ti y su alma te bendiga.
Ama a tus hermanas y sé amable con ellas siempre, y con tu hermano Thomas;
anímense unos a otros en el bien.

Y Abigail, si vives hasta alcanzar ser una mujer de edad madura,
guárdate sin mancha y no dejes que tu mente vaya tras deportes y pasatiempos,
porque el fin de todo eso es dolor; ni busques jóvenes.
Si deseas casarte, no busques marido, sino deja que el marido te busque;
y si tú vives una vida honesta y virtuosa en el temor de Dios,
entonces los que temen a Dios te buscarán. No dejes que
tus afectos vayan tras de todos los que te ofrecen amor,
sino sé prudente; y por encima de todo (si te casas) escoge uno que ame y tema al Señor,
cuya conducta, costumbre y curso de vida conozcas bien, antes de darle tu consentimiento.
Sé discreta y sabia.
No le ocultes nada a tu madre, y ella sin ninguna duda te aconsejará para tu bien;
y si ella está viva, no te cases sin su consentimiento.
Y si te unes a un marido, asegúrate de amarlo en tu corazón y sé obediente a él,
y hónralo en presencia de todos;
así su corazón será más para ti y su amor aumentará. No lo entristezcas,
sino sé amable y fácil de tratar, ocupándote de tus propios asuntos.
Y si el Señor les da niños, críalos en el temor de Dios y en buena disciplina,
manteniéndolos en sujeción a ti.
Sé un ejemplo de virtud y santidad para ellos,
para que sientas la bendición del Señor en tu juventud,
en la vejez y durante toda tu vida.

¡Oh, Abigail, recuerda estas cosas; tenlas presentes!
Lee a menudo esta carta; hazla copiar.
Guarda mis palabras en tu corazón y hazlas; así serás feliz en esta vida y en la porvenir.
Te encargo que guardes estas cosas, como expresión de mi mente,
voluntad y consejo inalterables para ti; en testimonio de lo cual pongo mi mano.

[.signed-section-closing]
Tu querido padre,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
26 del mes Quinto de 1666

--

Cerca de dos días antes de su partida,
siendo atendido por su querida esposa y varios amigos, les dijo: "`Amigos,
en relación con las palabras, no deben esperar mucho más de mí,
ni hay ninguna gran necesidad de ello;
solo que se acuerden de dar mi tierno amor a todos los amigos que preguntan por mí,
porque siempre he amado mucho a los Amigos,
o cualquiera en quien la Verdad haya aparecido.
Y en verdad Dios reconocerá a todos los que son fieles.
Y en cuanto a mí, estoy bien, y contento de morir.`"
A menudo en el transcurso de su enfermedad, repitió esta declaración,
que él estaba contento de morir, o que él estaba listo,
y alababa a Dios por los dulces gozos y refrescamientos
que había recibido en la cama de su celda,
donde yacía,
perdonando libremente a todos los que estuvieron involucrados en su confinamiento.
Él dijo: "`Este fue el lugar de mi primer encarcelamiento por la Verdad,
aquí en este pueblo, y si este será el lugar en el que dejaré el cuerpo,
estoy contento.`"
Varias personas reconocidas, habitantes de Appleby, como el alcalde y otras personas,
fueron a visitarlo en su enfermedad,
y cuando algunos oraron que Dios hablara paz a su alma, él respondió dulcemente:
"`Él lo ha hecho.`"

Unas pocas horas antes de su partida,
algunos amigos que vivían a varias millas de ese lugar fueron a visitarlo.
Él preguntó por el bienestar de todos ellos,
y oró fervientemente con muchas expresiones celestiales que el Señor, por Su gran poder,
los preservara de todas esas cosas que los contaminarían y mancharían. Y un poco después,
recuperando algo de fuerza, dijo: "`He buscado el camino del Señor desde niño,
y he vivido con inocencia entre los hombres;
y si alguno pregunta respecto a mi postrimería,
háganle saber que morí en la fe en la que viví,
y por la cual sufrí.`" Después de estas palabras, dijo algunas otras en oración a Dios,
y terminó dulcemente su curso en mucha paz, en el 20 del mes once de 1668,
a los cincuenta años,
después de ser un prisionero por el testimonio de
Jesús desde el final del quinto mes de 1663.
