== Prefacio por el Editor

Francis Howgill (1618-1668) fue un miembro prominente y antiguo
de la Sociedad Religiosa de Amigos (Cuáqueros) en Inglaterra.
Las obras coleccionadas de Howgill fueron primeramente publicadas en 1676,
ocho años después de su muerte, en un gran volumen titulado:
"`El Amanecer del Día del Evangelio, y su Luz y Gloria Descubierta.`"
Un compendio de este extenso volumen fue publicado en 1832 por James Backhouse,
el cual contenía, entre otros escritos, una versión resumida del ensayo titulado,
"`Algunos de los Misterios del Reino de Dios Declarados, etc.`"
El documento que tiene a mano no es la versión de Backhouse de este ensayo,
sino una versión menos abreviada que transcribí a partir
de una fotocopia de la publicación original de 1676.
Debido a que el estilo,
la puntuación y la ortografía utilizados en el inglés moderno temprano
difieren considerablemente del inglés de hoy en día,
una medida de revisión fue inevitable en la preparación de un manuscrito legible.
Sin embargo,
considero que esta publicación representa la versión más precisa y completa del
ensayo de Howgill que cualquier otra que esté disponible actualmente.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
Julio, 2015
