== Al Lector

[.salutation]
Lector,

En tiempos pasados, en la noche de la ignorancia, desde los días de los apóstoles,
muchos han andado a tientas en la oscuridad como hombres ciegos,
y de las densas tinieblas han hablado oscuramente de las cosas de Dios y de Su reino.
Estos han escrito sobre las cosas de Dios y Su reino,
y han alimentado las mentes oscuras de muchos que no han sido convertidos a Dios.
Muchos por lo tanto, están confundidos en sus mentes, y se equivocan en el juicio,
y han perdido la llave del conocimiento que abriría sus corazones
y les daría entrada a los misterios del reino de Dios.
Por lo tanto, en compasión por aquellos que están sedientos del Señor,
y por el bien de aquellos que no tienen un lugar dónde descansar,
he escrito estas cosas a medida que fueron reveladas a mí y en mí, por Su Espíritu puro.
Si esperas en esa luz a través de la cual Dios revela
Su mente y manifiesta Su conocimiento en el hombre,
y sales de la naturaleza del mundo, verás que estas cosas son verdad,
aunque se encuentren ocultas y veladas del mundo que yace en la maldad.

No he escrito para complacer a los hombres de mentes
corruptas que se glorían en las palabras,
en las apariencias externas, en las capacidades y los sonidos naturales,
y que se han extraviado de la Vida; sino más bien a los simples de corazón,
y para el fortalecimiento de los débiles, y para el entendimiento de los simples.
Y si hay algo en el siguiente discurso que no puedas aceptar, déjalo en paz,
y no juzgues nada antes de tiempo--en tu sabiduría que es terrenal,
o en tu propia razón. Más bien,
espera para poder juzgar por medio de aquello que
es de Dios en ti (en y por el cual deseo ser aprobado,
y por nada más),
y se manifestará en el Día del Señor que está amaneciendo en el mundo
(que muchos han visto aparecer en poder y gloria.) Entonces espera,
en tu propio corazón,
para que puedas sentir tu propia condición y apreciar tu propio estado.
Y luego, esa luz que te permite ver tu propia condición,
también te permitirá ver al Señor, y sabrás que lo que he declarado de Él es verdadero.

[.signed-section-closing]
Soy tu amigo en la Verdad, y deseo bien a todos los hombres,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
1658
