== Sección I.

[.blurb]
=== Algunos de los misterios del Reino de Dios declarados.

El Señor Dios de toda la tierra, quien vive por siempre, es decir, el Dios de Abraham,
Isaac y Jacob, cuyo trono está establecido en justicia,
que cabalga sobre los cielos y brilla en Su gloria
eterna desde el firmamento de Su poder,
se está manifestando como en los tiempos antiguos.
Él ahora está revelando Su justicia como en los años pasados,
y está derramando Su Espíritu sobre Sus hijos e hijas,
según Su promesa y Su bendición "`con el fruto más fino de los montes antiguos.`"^
footnote:[Deuteronomio 33:15]
El Señor, que apareció en Sinaí en la zarza ardiente a Moisés Su siervo,
que se levantó del Monte de Seir, y resplandeció en Su esplendor desde el Monte de Parán,
y viene de entre diez millares de santos; es decir,
Él de cuya mano derecha salió una ley de fuego,
de modo que las personas no podían contemplar Su gloria,
Este ha aparecido ahora en este Día de Su poder, y aún está apareciendo.
Su gloria deslumbrará los ojos del mundo y Su esplendor opacará la gloria del mundo,
y manchará la sabiduría del mundo, encerrándola en la más densa oscuridad,
de modo que parecerá que no tiene existencia ni ser.
La sombra de muerte huirá,
todos los príncipes soberbios y altivos de este mundo tendrán un temor horrible.
Las bestias entrarán en sus guaridas cuando el Día aparezca,
y saldrán los corderos del redil eterno, y serán alimentados en los valles fértiles,
donde los manantiales de la vida estarán cerca de todas las riberas,
y los corderos se regocijarán en su Pastor, y dirán: "`El Señor es mi Pastor.`"^
footnote:[Salmo 23:1]
Porque, ¿quién ha visto Sus maravillas y nobles obras desde los días de antaño,
de las cuales los padres (que han dormido y descansan en el Señor) nos han hablado?
Pero ahora Dios está trayendo a muchos para que vean
la verdad de lo que los padres experimentaron,
y para que lo mismo se cumpla en ellos.
Honor y alabanza a Él que es el soporte y la fortaleza de todo Su pueblo para siempre.

El Día del Señor ha amanecido,
y ha aparecido la luz que manifiesta todas las cosas que son reprobables.
El Lucero de la mañana se ha levantado en los corazones de muchos,
y ellos han llegado a ver eso que Pedro los exhortó a esperar,^
footnote:[2 Pedro 1:19 "`Tenemos también la palabra profética más segura,
a la cual hacéis bien en estar atentos como a una antorcha que alumbra en lugar oscuro,
hasta que el día esclarezca y el lucero de la mañana salga en vuestros corazones.`"]
cumplido en sus corazones.
Estos han prestado atención a la palabra profética más segura
hasta que el Día apareció y esclareció en sus corazones.
Y este Día (cuando aparece, y a quién aparece) descubre todas las cosas,
y hace que todas las cosas se manifiesten,
como lo declara el Espíritu de Verdad en las Escrituras
de la Verdad--"`la obra de cada uno se hará manifiesta;
cual sea, de la naturaleza que sea.`"^
footnote:[1 Corintios 3:13]
Alabado sea el Señor,
porque este Día ha aparecido a muchos que lo han
esperado y ahora ven todo según su origen e incremento,
y cada árbol y fruto es visto según su género, ya sea bueno o malo.
Porque la obra de cada hombre es obvia para aquellos que están en el Día,
y sobre quienes ha aparecido la mañana de justicia y brilla el sol de justicia.
Así puede ser visto por todos (en la Luz que verdaderamente es llamada Día,
y por el Señor que hace que brote de lo alto) lo que es reprobable y condenable,
y también lo que es justificable e irreprochable.
Todo se ve cuando el Día del Señor aparece en el corazón.
