== Sección II.

[.blurb]
=== Lo que es el Día del Señor, cómo se ve y a quién ha aparecido.

Dios es espíritu, Su Día es espiritual y es visto con ojos espirituales.
Es luz pura, resplandor puro, el brillo puro del Señor en Su gloriosa excelencia.
Es el resplandor de la eternidad.
Es la vida manifestándose en resplandor.
Es la santidad derramándose en su propia gloria y pureza,
esparciéndose a sí misma en su inmensurable excelencia,
y solamente puede ser vista tal y como es por los hijos de la luz que nacen de ella.

Existe un día natural y un Día espiritual.
El día natural recibe su brillo del sol;
el Día espiritual recibe su brillo del Sol de Justicia (que es la Fuente de Vida),
por quien se produce, y sin el cual nada es hecho o producido.
El día natural recibe su claridad del sol natural,
y se discierne por el ojo natural del hombre natural,
y todas las cosas naturales son vistas y descubiertas por y en el día natural.
Asimismo, son claras y obvias para aquel que tiene la vista natural.
De la misma manera, el Día de Dios recibe su brillo del Sol de Justicia,
el Señor de la gloria, la luz y la pureza.
Sale de Él mediante los rayos de Su resplandor y es discernido y es visto solamente
por el ojo espiritual del hombre espiritual que es la imagen del Padre,
engendrado en Su vida y en Su propia naturaleza y calidad.
Este es el nacimiento que proviene de lo alto (de Dios el Padre de vida,
por Jesús la vida de los hombres y la luz del mundo).
Sólo el que es de la naturaleza del Padre y del Hijo, y de su Día,
llega a contemplar este Día y a discernir todas las cosas del reino del Padre
por medio de él. Este puede discernir todas las cosas ocultas y vergonzosas,
y las obras de la oscuridad que son producidas por el príncipe de las
tinieblas--que está encerrado en la oscuridad eterna y absoluta,
que es su eterna residencia y lugar de morada,
y será la residencia eterna de todos los hacedores de iniquidad que llevan su imagen.

[.discourse-part]
Objeción: Sin embargo, algunos pueden estar listos para decir,
"`¡Pero todas las cosas aún no han sido hechas manifiestas, ni ha llegado ese Día aún,
ni se le ha aparecido a nadie en esta era!

[.discourse-part]
Respuesta:
Qué pasaría si un hombre que es naturalmente ciego dijera
que no hay luz en el día natural ni en el sol,
simplemente porque él no ve ninguna.
¿No hay entonces luz en el día o en el sol?
Y, ¿qué pasaría si todas las cosas parecen ser similares para él,
tanto el día como la noche, porque no puede distinguir nada?
Entonces,
¿esto invalida el ver o impide el discernimiento de aquellos que
realmente están viendo tanto el sol como el día con el ojo natural?
Igualmente, ¿qué pasaría si ellos que son ciegos espiritualmente y son hijos de la noche,
dijeran que no pueden ver nada del Día del Señor, ni descubrir las cosas de Dios,
o Su gloriosa aparición, de la cual muchos otros dan testimonio?
¿Invalida esto la visión espiritual de aquellos que han visto las cosas del reino de Dios?
Que Dios no permita que la incredulidad de algunos
invalide la fe de aquellos que sí creen.
