== Sección III.

=== Lo que es el Día del Señor, y lo que será para los impíos.

El Día del Señor es luz y esplendor puros en sí mismo, y no se mezcla con la noche,
que es de una naturaleza contraria.
El Señor separó estas dos en el principio, estableciendo sus límites y moradas,
y determinándolo como un decreto que durará por toda la eternidad.
Pero a pesar de que el Día del Señor es puro, y mantiene su pureza,
carácter y naturaleza, (siendo consistente en sí mismo,
ya que nada puede alterar su pureza), aun así, es un Día de tinieblas y de oscuridad,
y un Día espantoso para los impíos que odian su aparición y su luz.
Porque a los hijos de mentira y engaño, cuyas obras son malas,
el Día los manifiesta tanto a ellos como a sus obras, les es tal y como está escrito:
"`Porque la mañana es para todos ellos como sombra de muerte.`"^
footnote:[Job 24:17]
La aparición del Señor los asusta, y ellos buscan huir lejos de ella.
Porque son como un ladrón que cava a través de una pared y se mete a hurtar
en una casa en la noche cuando el sueño profundo está sobre los hombres.
Pero cuando el día aparece, descubre sus acciones y tiene miedo porque puede ser visto.

Ahora, a todos los que viven sin temor sobre la tierra,
cuyos corazones están determinados a buscar la iniquidad como un tesoro escondido,
el Día del Señor vendrá sobre ellos como un ladrón. Y porque son hijos de la noche,
y producen los frutos de las tinieblas (que son contrarios a los de la luz),
tendrán su porción en la oscuridad total y la venganza eterna los rodeará como un muro,
y con furia, el fuego los devorará como pasto.
Así perecerán los impíos y tendrán su porción con los hipócritas.

¡Consideren entonces y arrepiéntanse,
todos los que vituperan y riñen en contra de la luz y de la aparición de Dios!
Porque el asna montés que está acostumbrada al desierto sigue sus deseos,
y los que la buscan no se fatigarán de buscarla;
porque saben que en el tiempo de su celo la hallarán y la capturarán fácilmente.^
footnote:[Jeremías 2:4]
De la misma manera,
aunque todos los impíos corran como el asna montés
y sigan su camino como el camello veloz,
a pesar de todo, llegará el momento, llegará el Día,
en que serán alcanzados en medio de la seguridad
y no escaparán. Y aunque los hijos de este mundo,
maestros de este mundo y los profesantes del cristianismo (que
profesan las Escrituras) hayan orado por el Día del Señor,
no obstante, cuando llegue, será como un fuego ardiente,
un fuego consumidor y caerán como tamo y como un monte ardiente
delante de él. Ellos no serán capaces de permanecer,
porque todo lo que es reprobable es manifiesto por el Día, por la luz que es eterna,
en la cual Dios aparece.
Y este Día aparecerá aun para los impíos y los malvados,
y ellos serán manifestados (porque lo que es hecho manifiesto ya no está oculto,
sino que es visto, revelado) y contemplado.

Por lo tanto, todos los asalariados que predican por precio,
y el pueblo que así lo quiere, no se esconderán. Todos los que se opongan a la verdad,
serán descubiertos y convencidos de sus obras impías y palabras duras,
y eso que los manifestará será el Día,
y ciertamente los convencerá. Porque aun los malos verán su aparición,
aunque para condenación, vergüenza y menosprecio.
"`Mirarán al que traspasaron.`"^
footnote:[Zacarías 12; Juan 19:37]
Porque incluso en los malvados, Dios tiene un testigo que es puro,
que a menudo los reprende, aunque no lo consideren,
porque el dios del mundo ha cegado sus ojos.
Sin embargo, cuando Cristo, la vida, se manifieste,
Él hará que ese ojo (que los impíos han cerrado y que el dios del mundo ha cegado) vea.
Por Su poder, el Señor incluso abrirá los ojos de los impíos,
y ellos Lo verán a Él y a Su venida en temor,
y Su aparición pura los atemorizará terriblemente, y Su Día y aparición será su angustia.
Aunque ellos no quisieron ver, serán obligados a ver,
y a escuchar eso que ellos rechazaron escuchar,
cuando Dios haga sonar Su trompeta y dé aviso a todos,
que los muertos (tanto pequeños como grandes) deben levantarse, "`unos para vida eterna,
y otros para vergüenza y confusión perpetua.`"^
footnote:[Daniel 12:2]

Por lo tanto, no pongan esta advertencia lejos de ustedes,
todos los obreros fraudulentos, adúlteros e idólatras,
que adoran sus propias imaginaciones,
y todas las personas confiadas que viven en ligereza y placer,
que son complacientes de hombres, habladores de vanidades,
bufones tontos y despreciadores de aquellos que han salido
de la contaminación en la que ustedes se revuelcan.
De hecho, la aparición del Señor será su gran regocijo, pero para ustedes,
será vergüenza y miseria eterna, a menos de que se arrepientan rápidamente.
