== Sección IV.

=== Lo que el Día del Señor es para los justos, y cómo Él se les aparece, y si alguno debe buscarlo estando todavía en el cuerpo.

La aparición de Dios (que es la vida eterna) en Su Día, en Su luz inconmensurable,
es un gran gozo y una fuente de regocijo para los justos.
Porque Él es, para su pueblo que lo contempla, una luz eterna, y en Su luz,
ellos verán la luz.
Asimismo, en Su Día, Él revela los misterios secretos de Su reino en su interior,
es decir, en aquellos que ven el Día aparecer en sus corazones.

Este Día hace todas las cosas manifiestas,
incluso los secretos del Señor y Sus tesoros escondidos,
que nunca se pudren ni se oxidan, sino que siempre son frescos,
y mantienen su imagen e impresión pura, y son siempre los mismos.
Por medio de esta luz, todos los justos que han esperado por la aparición de Dios,
llegan a verlo, tal como está escrito: "`Este es Jehová a quien hemos esperado,
nos gozaremos y nos alegraremos.`"^
footnote:[Isaías 25:9]
¿Qué? ¿De verdad ha llegado Aquel a quien han esperado?
Sí, Él ha llegado, "`he aquí su recompensa viene con Él.`"^
footnote:[Isaías 40:10; 62:11]
Los que lo ven encuentran contentamiento en Él y en Su recompensa.
Y, ¿cuál es la recompensa?
Es gozo, alegría, paz de consciencia,
certeza del amor de Dios sellado en el corazón por el Espíritu puro del Señor.
La recompensa es como ríos de vida fluyendo continuamente desde las grandes profundidades
que refrescan el alma y la mantienen fresca en el mayor calor y tentación. Esto
es disfrutado por aquellos que han esperado,
y que lo esperan,
incluso ahora en el cuerpo--estos pueden dar testimonio de Él y de Su venida.

Porque, ¿cuál fue el testimonio de los discípulos?
No fue, "`el Hijo de Dios ha venido, y nos ha dado entendimiento.`"^
footnote:[1 Juan 5:20]
¿Un entendimiento de qué? De Dios, de Su Día, de Su aparición, de Su poder,
de Su sabiduría, de Su reino, de esperanza, fe, certeza, paz, gozo,
consuelo y consolación. ¿Qué, en esta vida?
Sí, ¡en esta vida!
Podría traer una nube de testigos de épocas pasadas,
y también una nube de testigos de esta era, ¡alabado sea el Señor!
Sin embargo,
mi testigo (Aquel que me da certeza) está más cerca
de mí y es más seguro para mí que todos estos testigos,
aunque todos ellos son verdaderos.

Abraham, el padre de los fieles y los justos, que creyó en Dios y fue aceptado,
él "`vio el Día de Cristo, y se gozó.`"^
footnote:[Juan 8:56]
Los profesantes objetan--"`¡Pero eso fue por fe!`"
Sí, por supuesto, ¿por qué otra cosa?
Por la fe Abraham vio, y por medio de la fe todos los demás han visto,
quienquiera que verdaderamente haya visto a Cristo, o Su Día, o al Padre.
Por la fe vieron a Aquel que es invisible.`"^
footnote:[Hebreos 11:27]
"`He aquí Dios es salvación mía.`"^
footnote:[Isaías 12:2]
¿Qué, disfrutas ya de la salvación? Sí, "`Dios se ha vuelto mi salvación.`"^
footnote:[Éxodo 15:2; Salmos 118:14; Isaías 12:2]
Asimismo Simeón, que esperaba la consolación de Israel, dijo: "`Ahora, Señor,
despides a Tu siervo en paz, porque han visto mis ojos tu salvación.`"^
footnote:[Lucas 2:29-30]
Y el apóstol, conociendo el consuelo y la consolación de Dios, dijo esto:
"`Porque de la manera que abundan en nosotros las aflicciones de Cristo,
así abunda también por el mismo Cristo nuestra consolación.`"^
footnote:[2 Corintios 1:5]
De hecho, estos fueron hechos partícipes de Su naturaleza divina,
y se sentaron juntos en lugares celestiales en Cristo Jesús. Porque el Cielo es Su trono,
y los que están en Él y lo gozan,
(quien es el poder y la sabiduría de Dios) conocen la paz, y el descanso,
y la salvación tanto de la culpa como del pecado.
Igualmente el apóstol, al escribir a los hebreos dijo:
"`Habiendo efectuado la purificación de nuestros pecados`" (hablando de la expiación),
"`el eterno Sumo Sacerdote se sentó a la diestra de la Majestad en las alturas.`"^
footnote:[Hebreos 1:3]
Pablo vio más allá del pecado, incluso hasta Aquel que había purificado el pecado,
y esta purificación del pecado se manifiesta a y
en aquellos que creen por el Espíritu de Jesús,
que es Cristo el Señor, el Brazo que trae la salvación,
y el Autor de eterna salvación para todos los que creen.
Él comienza la salvación en Su Día, y Él la perfecciona en Su Día;
porque Él trabaja en el Día, como Él mismo ha dicho: "`Mi Padre hasta ahora trabaja,
y yo trabajo, pero la noche viene, cuando nadie puede trabajar.`"^
footnote:[Juan 5:17; 9:4]
Y esta es Su obra en el hombre--"`deshacer las obras del diablo.`"^
footnote:[1 Juan 3:8]
Asimismo aquellos que han venido a Su Día sienten y ven la obra de Dios en sí mismos,
y Sus propias obras lo alaban, porque solo ellas pueden hacerlo.
Pero, aquellos que no han venido al Día, no conocen la obra de Dios en ellos mismos.
Y aquellos que aún no han prestado atención a esa luz en
sí mismos (que manifiesta todas las cosas reprobables),
no han llegado a conocer la aparición del resplandor de la luz, o del Día,
que los santos experimentan en sí mimos, es decir todos aquellos que son santificados.
