== Sección V.

=== Dónde aparece el día del Señor, cómo viene, y cómo debe ser buscado.

Aquellos que buscan en lo externo, cuyos ojos están en lo de afuera,
no pueden ver la aparición del Señor o Su Día. El que no sabe en qué consiste este Día,
no puede saber cómo buscarlo,
así como los judíos que eran profesantes de la Escritura y hombres eruditos,
no sabían en qué consistía el reino de Dios.
De la misma manera, los profesantes literales de la religión de hoy día,
cuya fe está fundada en la letra escrita y en lo cual es visible,
no pueden entender lo que digo.

Antes que todo, uno debe saber en qué consiste este Día:
Es el eterno resplandor esparciéndose a través de todas las cosas,
que penetra a través de los lugares más secretos, y los escudriña y manifiesta,
incluso eso que es invisible.
La naturaleza de todo llega a ser vista en el Día del Señor,
y este Día irrumpe y aparece en el corazón. Es ahí
donde el hombre debe esperar que el Día amanezca,
y buscar la luz que manifiesta todo mal,
y declara en contra de todo lo que es contrario a su propia naturaleza.
Entonces Cristo--el Pacto de Luz, el Don de Dios,
el enviado y ungido de Dios para proclamar el año agradable del Señor y el Día de la
venganza--es Él el que amanece y proclama en el corazón. Él no viene a traer paz,
sino una espada, y Su espada es la espada del Espíritu.
Es esta espada que divide y discierne las intenciones del corazón,
y este Día que descubre la perversidad del corazón. Asimismo, en el corazón terrenal,
en donde Él no encuentra fe, Él enciende un fuego y ejecuta Su venganza.
Para tales personas,
el Día del Señor es un Día de gran confusión. Sus espíritus llegan a ser heridos;
sus corazones se desmayan; la tristeza los inunda y la aflicción es sentida.
Esta es la condición de todos los que son inconversos,
en quienes Él no encuentra fe ni esperanza en el corazón,
entonces Él viene y les quita la paz.
Muchos han hablado del Día del Señor, pero cuando llegue el momento de acercarse,
no podrán soportarlo.
"`Porque la luz es lo que manifiesta todo.`"^
footnote:[Efesios 5:13]
Pero cuando la maldad y el engaño salen a la luz,
entonces los que han hecho el mal no pueden permanecer en ella.
Correrán hacia cualquier otra cosa en lugar de permanecer en el Día,
o de mirar al Señor de la vida apareciendo para ejecutar la venganza sobre Sus enemigos.

Aquellos que aún no han visto este Día de la venganza del Señor en sí mismos,
no pueden ver el Día de la salvación. El profeta declaró:
"`¿Y quién podrá soportar el tiempo de su venida?
¿o quién podrá estar en pie cuando él se manifieste?`"^
footnote:[Malaquías 3:2]
Sin embargo, muchos ya han sido testigos presenciales del terrible Día del Señor,
que ha aparecido, y en el cual toda paz ha sido oculta de sus ojos.
Porque en verdad, todos los que alguna vez vinieron a ver el Día de gozo y felicidad,
primero tuvieron que haberse enfrentado con el Día terrible del Señor en sí mismos.
Por esta razón el apóstol dijo: "`Conociendo, pues, el terror del Señor,
persuadimos a los hombres.`"^
footnote:[2 Corintios 5:11 RV 1602 Purificada]

Ahora, este Día no viene con una observación externa, "`Helo aquí,
o helo allí,`" porque de esta manera los fariseos esperaron la venida del reino,
incluso cuando Cristo les dijo que se encontraba dentro de ellos.
También les digo, si alguno desea contemplar el resplandor de la luz eterna,
deben esperarlo en eso que es puro de Dios,
a través de lo cual Él manifestará Su Día y Su poder en ustedes.
En la medida que mantengan su mente puesta en esa
luz que manifiesta el mal y les muestra el bien,
verán cómo aparece:
"`Porque como el relámpago que sale del oriente y se muestra hasta el occidente,
así será también la venida del Hijo del Hombre.`"^
footnote:[Mateo 24:27]
El ojo que es espiritual lo ve,
porque el poder y la gloria del Señor llegan a verse en
el Día que es puro y espiritual en el corazón. De hecho,
el ojo que es puro sabe cuándo este viene, de dónde viene y cómo viene.
Pero está oculto de los ojos de buitre, y de los ojos llenos de adulterio,
y de aquellos que no pueden cesar de pecar.
El Día del Señor no viene donde la mente carnal pueda imaginarse,
ni según la voluntad del hombre,
ni de los deseos carnales del corazón. Para el ojo maligno que busca externamente,
el Día no puede ser visto, sino que es visto en la luz propia de Dios,
según la medida del Espíritu Santo de Dios.
Y como el Día del Señor es un misterio,
así también el Espíritu del Señor es el único que lo descubre,
porque "`nadie conoció las cosas de Dios, sino el Espíritu de Dios.`"^
footnote:[1 Corintios 2:11]

Verdaderamente, el Día del Señor, y Su resplandor brillando en el corazón del hombre,
es una de las cosas gloriosas de Dios que solamente el Espíritu de Dios
(y no la mera letra de la Escritura) se hace conocer al hombre en el hombre.
Porque los judío tenían la letra,
pero no habían escuchado la voz de Dios en ningún momento, ni habían visto Su aspecto.
A través de las palabras escritas no habían ni visto el Día del Señor,
ni conocido Su poder, o percibido a Dios, o los misterios de Su reino.
Más bien, soñaron, imaginaron, pensaron y concibieron cosas en sus mentes,
siendo oscurecidos sus corazones insensatos.
Porque cuanto más se aleja un hombre de la luz, su corazón se vuelve más y más oscuro,
y su entendimiento se cierra para que él no pueda contemplar al Señor y Su gloria.
Estas cosas son reveladas solamente por el Espíritu Santo de Dios,
cuyo Espíritu está cerca del hombre, aunque este no lo vea.
