== Sección VI.

[.blurb]
=== Qué es el Espíritu de Dios que descubre las cosas de Dios, y cómo se recibe.

El Espíritu del Señor, que es uno con el Padre y el Hijo, es la pureza misma,
la santidad misma.
Es poder puro, fortaleza pura, que no se mezcla con nada,
ni se une a nada excepto a lo que es de Su propia naturaleza.
Es sustancia espiritual pura e inconmensurable, es vida esparciéndose,
es un poder vivo y activo, que es eterno y nunca cambia,
manteniendo por siempre su santidad y pureza.
Es inescrutable, insondable e indecible.
Todas las palabras se quedan muy cortas y muy estrechas
para declarar Su excelencia y gloria,
pero se da a conocer,
se abre y se derrama a sí mismo en aquellos que creen y esperan
en Él. El Espíritu de Dios es revelado en Su propia pureza,
hecho manifiesto en Su propio poder,
recibido en Su propia luz y sentido en Su propia virtud.
El mismo Padre viviente de la vida se manifiesta por medio de Él,
y Él aparece en Su poder y majestad y excelencia
a través de Él a los hijos de los hombres--es decir,
a los justos e injustos, a los piadosos e impíos, a los rectos y a los engañadores,
a los hijos de las tinieblas y a los hijos de la luz.

El Espíritu es el que escudriña los corazones de los hombres,
quien ve a través de todas las cosas, y manifiesta todas las cosas,
tanto las cosas ocultas de Dios como las obras secretas de las tinieblas,
reprendiendo por todo mal e iniquidad.
Es el acto puro del Espíritu convencer a cada hombre de pecado,
y cuando la criatura se une con Él, Él se levanta y resplandece más claramente,
dándose a conocer en su Su poder y obra.
Su poder llega a sentirse a medida que reprende y reprueba,
que juzga y condena todas las acciones pasadas, trayéndolas a la memoria.
Y conforme se espera en Él y se obedece,
el Espíritu se derrama a Sí mismo en Su propio resplandor puro,
sacando todas las cosas a la luz, y manifestando las intenciones de la mente.

Ahora, mientras uno espera en la aparición pura del Espíritu, y la mente está quieta,
tranquila y calmada, la criatura llega a sentir, y a conocer sensiblemente,
su propia condición. Él ve que su mente está viva para otras cosas, para otros amantes,
y no para Dios, y entonces reconoce que está muerto para las cosas del reino de Dios,
y que aún está en la caída y en la transgresión. Ahora,
eso que muestra los movimientos y pensamientos vanos, y los reprende,
es la obra del Espíritu,
y Su pureza se llega a sentir obrando en el corazón.
Y a medida que esta obra es amada y obedecida,
conduce y convierte el corazón al Señor, atrayéndolo hacia Sí Mismo,
fuera de la impiedad, y fuera del poder oscuro,
poniendo toda la oscuridad debajo de él. Y entonces el Espíritu
se levanta en Su fuerza (como es creído y esperado),
y juzga y condena todo mal.
Porque el Espíritu es el que descubre la mente del Señor a los hijos de los hombres,
y por medio de Él, el Padre da a conocer Su mente a y en la criatura,
revelando las cosas que son eternas en Su carácter y naturaleza.
Solamente aquellos que tienen el Espíritu y son sacados de la sensualidad,
llegan a discernir a Aquel que es invisible,
y conocen las cosas que pertenecen a la felicidad eterna.
Tales cosas no son vistas por el ojo natural,
ni son recibidas por el espíritu del mundo--porque
el mundo no puede recibir las cosas de Dios,
ni el testimonio de aquellos que están en Su vida.

Ahora,
todos los que llegan a recibir el Espíritu de la verdad deben esperar en eso que es puro,
y estar unidos a ello.
Porque el Espíritu no se une al hombre corrupto, al corazón sensual, a los afectos viles,
a aquellos cuyos ojos están llenos de adulterio.
No se une a la semilla de la falsedad, al nacimiento corruptible,
a eso que es nacido de la carne, ni a la voluntad de la criatura.
Sin embargo, aunque no se una a esto aun así se encuentra cerca del hombre,
incluso del hombre natural.
Su manifestación, o el resplandor de Su brillo,
hace que todas estas cosas se manifiesten como maldad.
Y para este propósito, el Espíritu de Dios ha aparecido al mundo,
para convencer al mundo de pecado.
Porque mientras el corazón de cualquier hombre está ocupado con pecado,
y se une a eso que la luz reprueba, no puede recibir el Espíritu,
ni poseerlo o disfrutarlo.
En cambio, el Espíritu se aparta tomando distancia de tal hombre,
manifestando tanto al hacedor de iniquidad como a sus obras de oscuridad.
Pero, en la medida en que un hombre se niega a sí mismo,
y se une a la manifestación del Espíritu de Dios (resplandeciendo en él con pureza,
y reprobándolo) recibe una medida del Espíritu de santidad,
y siente el poder de Dios en una pequeña medida (aunque débil) obrando en él
la purificación de esas cosas que el Espíritu le permite ver que son maldad.
Entonces, en cierta medida él siente y aprende en sí mismo qué esperar, y dónde esperar,
y en qué--a saber,
en aquello que le da a cada uno un sentido de su propia condición interna,
y abre su entendimiento.
