== Sección VII.

[.blurb]
=== Cómo opera el Espíritu de la Verdad en aquellos que están convencidos, y aun así no han obedecido.

Aunque Dios, que es Espíritu, ha aparecido por medio de Su manifestación a todos,
sin embargo, no todos lo han recibido.
El que odia la luz, no la ha recibido,
porque "`la mañana es para todos ellos como sombra de muerte.`"^
footnote:[Job 24:17]
Al hacedor de mal, no le gusta, no le presta atención,
ni recibe eso que manifiesta y lleva todo mal a la luz,
más bien permanece sin Dios en "`el mundo que yace en maldad.`"^
footnote:[1 Juan 5:19 RVG]
Él permanece muerto en delitos y pecados sin el Espíritu;
él sigue siendo un sepulcro en el cual el Justo yace asesinado.
En este estado Dios no es recordado, porque en la muerte no hay memoria de Él;
en el Seol ¿quién Lo alabará?

La luz resplandece en las tinieblas,
y el hombre que es convencido más no convertido es esas tinieblas,
a pesar de que eso que lo convenció es la luz.
Los disputadores argumentan: sólo los hombres buenos tienen luz,
pero no aquellos que producen las obras de las tinieblas.`"
Pero, aunque el hombre está en tinieblas, y es tinieblas, la Luz brilla en él,
el Espíritu de Dios resplandece allí en las tinieblas, manifestando su oscuridad.
Los efesios eran tinieblas en su estado no convertido, pero la luz brillaba en ellos^
footnote:[Efesios 5:8]. Ellos estuvieron una vez "`sin Dios en el mundo,`"^
footnote:[Efesios 2:12]
pero la Luz resplandeció en su oscuridad, y se volvieron a ella,
y se convirtieron en "`luz en el Señor.`"^
footnote:[Efesios 5:8]
Y Pablo dice: "`porque, que mandó que de las tinieblas surgiera la luz,
es quien brilló en nuestros corazones para que se revelara
el conocimiento de la gloria de Dios en el rostro de Jesucristo.`"^
footnote:[2 Corintios 4:6 H.B. Pratt 1929]
De modo que todos están sin excusa, porque "`no se dejó a sí mismo sin un testigo`"^
footnote:[Hechos 14:17 Traducción Literal de la KJV]
en ninguno.
Pero aquellos que no conocen el Testigo de Dios dentro de ellos,
esa luz que debería traerles la seguridad de salvación, les asegura su condenación.

Ahora, conforme cada hombre se vuelve a la medida del Espíritu Santo de Dios,
y mantiene su mente en ella, él llega a sentir y a ver su reprobación,
y mientras la mente se aferra a ella, el Espíritu se levanta en Su pureza,
haciendo resplandecer más brillo en el corazón. Este resplandor reprende desobediencia,
juzga y a medida que se le presta atención, aparece con fuerza,
dejando abierto cada corazón, mostrando cuánto abunda en ellos la injusticia,
las imaginaciones, la vanidad, los pensamientos ociosos y la lujuria.
De hecho,
cualquier cosa que la mente pueda buscar para experimentar placer por un momento,
aun así la medida del Espíritu de Dios siempre está presente para condenarla,
y los golpes del Todopoderoso caen pesadamente sobre la
espalda del que aún está en desobediencia al Espíritu.
Y aunque por un tiempo, el clamor del Espíritu no se escuche,
y por desobediencia parezca como muerto para el hombre, sin embargo,
si la mente está quieta, y el hombre está sobrio y tranquilo, ahí vuelve a aparecer.
Y aunque el hombre pueda tomar y realizar algo que es llamado religioso,
y orar con palabras, y leer y hablar de las Escrituras,
y practicar algunas ordenanzas externas y carnales, y contentarse en esto por un tiempo,
aun así, el Testigo del Espíritu Santo de Dios le muestra que es un hipócrita.
Aquel que busca cubrirse y protegerse mientras continúa
viviendo en desobediencia al Espíritu,
buscando estar tranquilo en la carne, este encontrará que todo es vano,
y que no hay paz en su corazón,
porque la medida del Espíritu Santo de Dios le muestra que aún le sirve al pecado.
De hecho,
si un hombre practicara todas esas cosas que otros
han hecho en el Espíritu y por medio de la Vida,
y en las cuales ellos fueron aceptados anteriormente por Dios, esto aun así no serviría,
porque Dios no se complace en esto, más bien le sería "`como si matase a un hombre,
como si degollase un perro, o como si ofreciese sangre de cerdo.`"^
footnote:[Isaías 66:3]
Todo esto es abominación para el Señor. E incluso si un hombre
pecara contra la luz de Cristo en su propia consciencia,
tanto que la luz se volviera para él como si no existiera tal cosa, aun así,
esto no sería excusa.
Porque el Señor tronará desde Su lugar santo, y le hará ver y escuchar,
a pesar de que haya tapado sus oídos y cerrado sus ojos.
Él hará que Su terror golpee en el corazón,
por lo que el temor lo rodeará como una pared,
y tendrá miedo de lo que verá y escuchará. Porque aunque
el Espíritu contiende por mucho tiempo con el hombre,
sin embargo la larga paciencia de Dios,
finalmente llega a un fin para aquellos que desobedecen,
y ellos tendrán su porción por siempre con los rebeldes
y los de dura cerviz en las profundidades del infierno,
por siempre entre los hijos de las tinieblas,
quienes no se han sometido a la guía del Espíritu.
Reflexionen en esto, porque es la verdad del Señor que les declaro.

Si persisten en las imaginaciones de su propio corazón y de su propia voluntad rebelde,
entonces ciertamente apagarán al Espíritu y Sus movimientos.
Y aunque el Espíritu es vida en Sí mismo, sin embargo está muerto para ustedes,
que están resistiendo esa luz a través de la cual el Eterno poder de Dios se manifiesta.
Seguramente se volverán indiferentes y perderán toda sensibilidad,
y serán cauterizadas sus consciencias, y serán inconscientes de las cosas de Dios,
y vendrá sobre ustedes dureza de corazón como una piedra que no puede ser derretida.
Ay de aquellos en quienes el Espíritu del Señor cesa de contender,
habiéndose rebelado tanto tiempo en contra de Sus movimientos puros,
y contristado al Señor. Porque el Señor finalmente entrega al hombre a sus afectos viles,
para que siga las imaginaciones de su propio corazón
("`que no recibió el amor de la verdad para ser salvo`"^
footnote:[2 Tesalonicenses 2:10]). Para aquellos
que han hecho afrenta al Espíritu de la gracia,
Su larga paciencia llega a su fin, y el ardor de Su ira se enciende,
y aquello que los habría llevado fuera del mundo a la verdadera paz eterna,
ahora se convierte en su atormentador.
Porque ellos son desterrados de Su presencia, y encerrados en eterna miseria,
donde el fuego es encendido por el aliento del Señor que arde por siempre,
"`porque se complacieron en la injusticia, y se vendieron para hacer lo malo,`"^
footnote:[2 Tesalonicenses 2:12; 1 Reyes 21:25]
crucificando la aparición de Cristo en ellos mismos.
Y esta aparición, aunque fue crucificada por ellos,
aún vive para siempre para ser su condenación eterna.
