== Sección VIII.

=== Cómo opera el Espíritu del Padre en aquellos que se vuelven a Él, y han prestado atención a Sus manifestaciones, y son, en cierta medida, partícipes de Su poder.

"`Hay diversidad de dones, pero el Espíritu es el mismo.
Y hay diversidad de ministerios, pero el Señor es el mismo.
Y hay diversidad de operaciones, pero Dios, que hace todas las cosas en todos,
es el mismo.`"^
footnote:[1 Corintios 12:4-6]
Ahora, el Espíritu de la Verdad, que es Vida en sí mismo,
no sólo opera para convencer al que transgrede en contra de Su aparición,
y para manifestar el mal que ha sido cometido, sino que también,
cuando el hombre se vuelve a Él y espera en Él,
le muestra cuando surgen los movimientos y las tentaciones al pecado.
Y mientras la criatura está quieta y espera en la luz que manifiesta todo,
y mantiene su mente únicamente hacia ella, el Espíritu derrama Su poder,
vence y subyuga los deseos que surgen, y condena la tierra de donde se levantan.
Obra secretamente, exhalando Su vida pura en el que espera en paciencia y quietud,
sin prestar atención a los pensamientos vanos e imaginaciones
que se levantan en su corazón,
sino más bien a la manifestación del Espíritu,
ante cuya aparición resplandeciente se extinguen todos los deseos vanos,
y se engendra un hambre internamente de ser hechos partícipes de Su naturaleza y pureza.

Porque Dios, a través de la obra de Su Espíritu eterno, deja salir Su poder,
que convierte y cambia el corazón,
corta y divide entre un hombre y los amantes a quienes se ha unido.
El Señor hace una separación interna,
y lleva al hombre lejos de esas cosas que el Espíritu reprueba,
guiando al alma más cerca de Dios.
Entonces, los que creen en la medida del Espíritu de Dios,
y esperan en ella diligentemente,
llegan a sentir lo que verdaderamente significa el arrepentimiento de las obras muertas,
porque tanto las obras como el obrero son manifiestos en la luz.

Ahora, para el que espera única y quietamente en el Espíritu,
no hay nada que pase por la mente excepto lo que puede ser
fácilmente discernido por el Único que da discernimiento.
Sin embargo, incluso después de que el Espíritu de verdad se siente en cierta medida,
y se conoce Su testimonio vivo,
podría pasar mucho tiempo antes de que haya un discernimiento claro en el entendimiento,
de tal manera que los movimientos del Espíritu puedan distinguirse claramente de todos
los movimientos falsos e imaginaciones elevadas que se han levantado por encima de ellos.
Pero las mentes apresuradas y adelantadas siguen
sus movimientos vanos que las conducen al engaño,
y entonces el interrogador se levanta,
y ellas cuestionan todo lo que hasta ahora el Espíritu les había manifestado.
Entonces el velo es puesto, y el enemigo se aloja en la oscuridad que ha entrado.
Y tan pronto como alguno escucha su voz, él pone deseos en su corazón para que los sigan,
y ellos son engañados por él. Por tanto,
todos deben mantenerse en la medida del Espíritu,
para que puedan sentir sensiblemente la diferencia entre
los movimientos y las persuasiones puras del Espíritu,
y los pensamientos vanos que surgen del corazón terrenal.
Y cuando aparece algo que la luz no respalda, no debe seguirse ni escucharse,
sino que debe mantenerse una espera silenciosa y quieta,
para que todas las cosas puedan aclararse para el entendimiento.
Por falta de esto, muchos han corrido delante de la luz,
y han hecho cosas apresuradamente en su propia voluntad,
engendrando la obra de Satanás. Estos han perdido el verdadero
sentido de lo que debería guiar sus mentes,
y en su lugar han seguido al espíritu de error,
causando que el Espíritu puro del Señor sea blasfemado.

Pero conforme uno espera en silencio, y se mantiene detrás de la luz, sin querer o correr^
footnote:[Romanos 9:16]
ni apresurarse,
entonces el Espíritu se levanta pura y quietamente
en el corazón y resplandece internamente en esplendor,
de modo que da evidencia perfecta y un testimonio pleno de Sí mismo,
para que no haya dudas ni cuestionamientos respecto a Su movimiento.
Ya que se mostrará claramente a Sí mismo en Su propio resplandor puro,
con plena certeza de Su propia voluntad.
Luego, después de que Sus movimientos sean claramente vistos,
permitan que todo razonamiento se mantenga sometido,
y todo cuestionamiento se mantenga lejos,
y no cedan el paso a la tentación. Porque esos movimientos del
Señor de la Vida los llevarán a cumplir la voluntad de Dios,
a través de Su propia operación y poder.
De esta manera, tendrán paz en la obediencia, y su fortaleza será renovada.
Pues en la medida que alguien es llevado a someterse
a la voluntad de Dios cuando es conocida,
y a obedecer por la virtud del propio poder de Dios,
entonces eso que está en él y que es contrario al Espíritu de Dios, pierde su fuerza,
y comienza a decaer y a debilitarse.
Pero cuando alguno desobedece el mover puro del Espíritu
Santo de Dios después de ser conocido,
el enemigo entonces se fortalece, y lo que es de la carne se nutre,
y el Espíritu (que brinda Su poder cuando se someten a Él) llega a apagarse.
Pero sepan esto: el Espíritu en Sí mismo nunca pierde Su pureza,
ni puede ser apagado en Sí mismo.
Él mantendrá Su propio Testigo contra ustedes, y nadie podrá detener Sus reprensiones.

Cuando el Espíritu es escuchado, obedecido, amado y creído, manifiesta Su poder puro,
que da fortaleza y sella paz a los obedientes.
De esta manera, la diversidad de operaciones del Espíritu llega a experimentarse.
Pero cuando es desobedecido y resistido, condena, juzga,
reprueba y sella condenación a los desobedientes.
Sin embargo, aunque Sus operaciones varían, no hay variación en el Espíritu en Sí mismo,
porque siempre es uno y el mismo.
En la buena tierra hace engendrar fruto para Dios.
Y en la tierra maldita, de la que surgen abrojos y espinas,
enciende un fuego que no se apagará. Pero en la medida
que haya una sumisión a la operación pura del Espíritu,
habrá un ardor y destrucción de todo lo que obstruye el crecimiento de la Semilla,
y una purificación del corazón de toda inmundicia de la carne y del espíritu.
Entonces el Espíritu forja a la criatura en Su propia imagen y naturaleza,
y forma y moldea a todos los que están en la fe a la imagen del Padre.
Es aquí donde el amor del Padre llega a ser derramado en el corazón.
Y así como la ira fue revelada por el espíritu de condenación,
así ahora la paz de Dios llega a gozarse, y Su consolación es esparcida grandemente,
en la cual hay un gozo puro para siempre.
