== Sección IX.

=== A quiénes el Espíritu da testimonio y sella tanto la seguridad del amor del Padre como la verdadera justificación con Dios.

Los que no han creído en Cristo, "`la Luz verdadera,
que alumbra a todo hombre que viene en este mundo,`"^
footnote:[Juan 1:9 RV 1602 Purificada]
no tienen el testigo del Espíritu de Dios dándoles testimonio dentro de ellos.
Únicamente por Él se engendra la vida,
por Su poderosa operación en aquellos que creen en Él. Él es la vida eterna misma,
y Su palabra es Espíritu y vida,
por la cual la nueva criatura es constituida y formada en los que creen.
A estos, Él manifiesta Su poder,
porque a Él (que es la vida de los hombres) le es
dado todo el poder en el cielo y en la tierra.
Nada fue hecho o creado sino por Él,
ni ningún hombre se ha apartado del pecado sino por medio de Él y Su gran poder.
La muerte es estar sin Él; en Él está la vida y la vida es la luz de los hombres.

Ahora, sólo aquellos que han nacido de la luz, y son engendrados por Aquel que es la luz,
pueden tener el Espíritu de Cristo (que es la luz) dando testimonio a favor de ellos,
y pueden tener la seguridad del amor del Padre.
Porque solamente aquellos que nacieron del Espíritu, y andan en el Espíritu,
son justificados por el Espíritu del Señor. La seguridad
del amor de Dios no se manifiesta a Sus enemigos,
sino a los que son nacidos y engendrados en Su propia imagen,
en Su propia semejanza y naturaleza, la cual es pura e incorruptible,
sin mancha ni contaminación. Estos nacen de la santa Semilla que es heredera de la promesa,
y conocen la esperanza viva que purifica el corazón,
y produce la respuesta de una buena consciencia en aquellos que sienten
y son testigos del lavamiento de la regeneración. Estos han conocido en
sí mismos el agua pura derramada sobre ellos que ha quitado las manchas,
marcas, inmundicias e impurezas.
Porque dondequiera que estas manchas e impurezas no hayan sido lavadas,
y el corazón no haya sido limpiado de ellas,
y donde este lavamiento no haya sido creído (ni se sienta la suficiencia de Dios,
y Su poder hecho manifiesto),
no puede haber verdadera seguridad del amor del Padre en el corazón,
ni el testimonio dado por el Espíritu y la seguridad de la justificación.
Porque donde el pecado permanece sin ser vencido ni removido,
allí el Espíritu del Padre condena el pecado,
junto con el que se ha unido a él y se ha hecho uno con él. Porque ningún pecado es
concebido excepto cuando hay un consentimiento y un acuerdo a la instigación del diablo.
Cuando una tentación surge, ya sea interna o externa,
puede haber una resistencia y una lucha en contra de ella por un momento.
Sin embargo, si el corazón no se mantiene cerca del Espíritu,
el enemigo finalmente encontrará la entrada y cautivará el entendimiento
de tal manera que haya un acuerdo y una unión con el adversario.
Así el Espíritu pronuncia la sentencia de condenación sobre el que se ha unido con la
ramera (convirtiéndose en una sola carne con ella) y que no está unido a Cristo la Simiente.
Porque cualquiera que se haya unido con la ramera y tomado de la copa de fornicación,
debe tomar también la copa de la ira y del temor,
y llevar el golpe de la justicia divina,
y permanecer bajo ella en paciencia hasta que sea cortado lo que
se haya unido al engaño. Sólo entonces hay remisión de la transgresión,
y la criatura es por tanto justificada ante los ojos de Dios.
Porque el pecado no se borra del libro de la memoria
de Dios hasta que uno se vuelva y se arrepienta;
sólo entonces la criatura es absuelta ante los ojos de Dios cuando Él juzga con
juicio justo--como testificará la luz en la consciencia de cada hombre.

Ahora, "`todo aquel que es nacido de Dios, no practica el pecado,
porque la Simiente de Dios permanece en él.`"^
footnote:[1 Juan 3:9; 5:18]
Esta Simiente es la vida,
y cuando la criatura se une con esta Simiente (que es la heredera
del reino y de la corona inmortal) viene a ser hecha partícipe
de su virtud y operación. La Simiente es Cristo,
y por Su poder limita a la semilla de la serpiente, y debilita su fuerza en la criatura.
Y a medida que el hombre llega a creer en la fuerza de la
Simiente (a quien se le ha encomendado todo el poder),
el pacto con la muerte se rompe,
y el acuerdo que la criatura ha hecho con la muerte llega
a ser nulo por el brazo y el poder del Señor. De esta manera,
la criatura llega a ser libertada de la esclavitud de corrupción,
y el nuevo hombre llega a vivir; es decir,
la nueva criatura (que es nacida de Dios y no peca)
llega a ser formada y moldeada a la imagen del Padre.
A este y en este, se manifiesta el amor del Padre, y él tiene la certeza en sí mismo.
Este niño que nace de arriba del Espíritu que es de arriba,
ha sido justificado por el Dios justo,
y tiene un registro de su justificación. "`Y tres son los que dan testimonio en la tierra:
el Espíritu, el agua y la sangre; y estos tres concuerdan.`"^
footnote:[1 Juan 5:8]
El que es nacido de eso que es puro tiene el testimonio de estos tres en sí mismo,
porque ellos concuerdan en uno.
De lo que uno da testimonio, los otros dos también. Además,
"`tres son los que dan testimonio en el cielo: el Padre, la Palabra y el Espíritu Santo;
y estos tres son uno.`"^
footnote:[1 Juan 5:7 RV 1602 Purificada]

Entonces, el que es nacido del Padre, y engendrado del Padre en Cristo la Simiente,
por medio del Espíritu, él, y solamente él,
llega a sentir el amor del Padre hecho manifiesto en él,
y es justificado ante los ojos del Padre.
Este tiene la seguridad y la evidencia cerca de él y en él, el sello del Padre,
el sello del Espíritu.
Así que cuando el adversario venga para tentar y atacar, y levante dudas en la mente,
la evidencia estará cerca, quitándole toda duda de que él está en el amor de Dios,
y es bendecido por siempre.
Bienaventurados son todos los que han esperado estas cosas, y las han sentido,
y son testigos de ellas, porque la carne y la sangre no las ha revelado.

Ahora, que todo hombre que lea esto se pruebe a sí mismo, y pruebe si está en la fe o no,
y si tiene la evidencia del Espíritu de que en verdad ha
nacido de Él. Que se pruebe a sí mismo si conoce el nacimiento
que no comete pecado porque la Simiente permanece en él,
y el maligno no lo toca, siendo guardado por el poder de Dios.
Porque tales personas se mantienen vivas para Aquel que las trajo a la vida,
y les ha dado de beber de la copa de la salvación,
que nutre para vida eterna a todos los que continúan en la fe.
