== Sección X.

[.blurb]
=== Lo que la gracia gratuita de Dios es, a quién se ha aparecido, y cómo deben esperar todos para recibirla.

[quote.scripture, , Tito 2:11-14 RVG]
____
Porque la gracia de Dios que trae salvación se ha manifestado a todos los hombres,
enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo, sobria, justa y piadosamente.
Aguardando aquella esperanza bienaventurada, y la manifestación gloriosa
de nuestro gran Dios y Salvador Jesucristo,
quien se dio a sí mismo por nosotros para redimirnos de toda iniquidad,
y purificar para sí un pueblo peculiar, celoso de buenas obras.
____

La gracia de Dios es un don puro, perfecto y gratuito de Dios.
Es la aparición de Cristo, el rayo de justicia que resplandece,
una medida de la fuerza y el poder de Dios que sale de Sí mismo.
Es una porción de Su tesoro, virtud y suficiencia que es esparcida en todos los que creen.
Es aquello, a través de lo cual Dios hace conocer Su voluntad, enseña,
y revela Su medicina salvadora a aquellos que son enseñados y creen en ella,
y se edifican en la verdad, y se convierten en una morada de Dios.
Ningún hombre tiene que hacer algo para comprarla.
Ninguno necesita decir, "`¿Dónde puedo conseguirla?`"
o "`¿Cómo puedo conocer su enseñanza?`"
Está cerca de ustedes, está dentro de ustedes;
"`se ha manifestado a todos los hombres,`" mostrando la
impiedad en el corazón del hombre a través de su resplandor.
Sí, les muestra a todos los hombres los movimientos del pecado.
Y todo lo que no es como Dios en sus movimientos, palabras, o acciones,
aleja el corazón del hombre como con una cuerda.
Muestra las lujurias del corazón y de la mente, "`los deseos de los ojos,
y la vanagloria de la vida.`"^
footnote:[1 Juan 2:16]
Nunca se une al pecado.
Nada puede alterar su pureza o propiedad, porque en sí misma siempre es una misma cosa.
Es perfecta,
y siempre lo será. Se mantiene alejada de lo que es corruptible e imperfecto,
y sin embargo lo ve.
Y aunque algunos que se han vuelto a ésta luego se han apartado nuevamente de ella,
y la han convertido (con respecto a sí mismos) en libertinaje,
aún conserva su pureza y reprueba toda lascivia, y lo pondrá ante ustedes,
mostrando cómo han abusado de la aparición de Cristo.

Muchos han hablado de la gracia de Dios en esta época de profesión religiosa,
pero no han conocido de lo que hablaron,
ni han dado a conocer a los hombres dónde se debe esperar, cómo se puede conocer,
ni cuál es su operación en el hombre.
En cambio, han aplaudido sus propias imaginaciones diciendo:
"`Somos justificados gratuitamente por Su gracia de todos los pecados pasados, presentes,
y futuros,`" y en esta vanagloria miles han sido llevados al hoyo de las tinieblas.
En esta oscuridad claman:
"`Somos justificados gratuitamente por la gracia de Cristo,`" pero
la gracia gratuita de Dios (si la hubieran conocido) les hubiera
enseñado que nunca le prestaron ni un poquito de atención,
sino que se levantaron en engreimiento, ligereza y presunción sin el temor de Dios.
Mientras afirman justificación,
ellos mismos son aún siervos del pecado y esclavos a la corrupción,
y este es el estado de miles en este día quienes han sido
predicadores y defensores de la gracia gratuita.
Y ahora, cuando la gracia ha sido experimentada por algunos,
y declarada (en cuanto a qué es, y dónde está),
estos ciegos guías y pastores ignorantes buscan matar a aquellos
que son alimentados y enseñados por el verdadero don de Dios.
Ellos engañan a las ovejas,
las esparcen del redil y las apartan del verdadero Pastor y de Su aparición
(que es Su gracia) y de Su voz (que es la Palabra de Su gracia),
que es capaz de salvar el alma.
¡Oh guías ciegos, ustedes que se hacen llamar hombres ortodoxos, y ministros,
que predican la gracia en palabras!
Ahora, por fin Dios les ha dado a los que han esperado en Él,
el entendimiento para declarar la gracia, y sin embargo ustedes claman:
"`¡La gracia no es un maestro suficiente!`"
Ahora, permítanme hacerles una pregunta:
¿Acaso la gracia que manifiesta la impiedad y enseña a negarla no es un maestro suficiente?
Si no es un maestro suficiente,
¿por qué el apóstol los dirigió y los encomendó a la Palabra
de gracia la cual es capaz de salvar el alma?
(Hechos 20:32). Respóndeme hombre sabio--¿Acaso no
es suficiente aquello que revela el pecado y la tentación?

Verdaderamente lo que revela el pecado es santo,
y lo que guía fuera de los deseos mundanos es puro, y lo que salva del pecado es gracia.
"`Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito al mundo.`"^
footnote:[Juan 3:16]
Él era y es la Luz del mundo, y ha derramado Su gracia, y la ha hecho aparecer a todos.
Y todos los que esperan en ella, y llegan a ser enseñados por ella, sienten su seguridad,
así que todos quedan sin excusa.
Por lo tanto, esperen en eso que se les ha aparecido.
Esperen en lo que muestra los deseos, pensamientos y movimientos hacia el pecado.
Este es el don de Dios, la gracia de Dios, y es suficiente,
aunque todos los hombres lo nieguen.
Todos deben esperar internamente,
para escuchar a Aquel que condena el pecado en la carne internamente,
quien por Su gracia le muestra al hombre su transgresión y la insuficiencia en sí mismo,
y por la Palabra de Su gracia salva del pecado, y le da dominio sobre el pecado.
Esto viene a revelarse en el corazón del hombre y allí, en lo que es puro, debe esperarse.
Ahí, en el corazón,
la gracia es recibida y es ahí donde se llega a experimentar su operación,
y donde participan de su virtud todos los que creen en ella, la reciben,
y están sujetos a la misma.
Estos ven y sienten la salvación de Dios revelada por medio de la gracia a sus almas,
y saben dónde reside su fortaleza--no en sus propios esfuerzos,
sino en el don gratuito de Dios, el don de la justicia,
el don justo por el cual la justificación viene sobre aquellos que creen.
