== Sección XI.

[.blurb]
=== Sobre si todos han recibido la gracia de Dios o no, y si es un maestro suficiente en sí mismo.

Esta generación sabia, cuya sabiduría está por debajo de la sabiduría de Dios,
ha confundido la mente de las personas con falsas
distinciones afirmando que hay dos tipos de gracia.
Primero, está eso que llaman "`gracia común,`" la cual ha aparecido a todos los hombres.
Segundo,
está eso que ellos llaman "`gracia especial y salvadora,`"
la cual sólo ha aparecido a los santos.
Por prestarle atención a estas distinciones (en tiempos pasados, muchos años atrás),
perdí a mi guía y a mí mismo,
pasando por alto Su aparición en mí y atendiendo a algo que estaba lejos de mí.
No le presté atención a la gracia que estaba en mi propia casa y cercana porque
fue llamada "`común e insuficiente,`" y de esta manera sufrí una gran pérdida.
Así que ahora soy movido por Él (ante cuyos ojos he encontrado Su favor,
misericordia y gracia) a declarar la verdad tal como
el Señor la ha hecho manifiesta a mí y en mí,
para que todos los que buscan al Señor sean informados y sepan
dónde esperar en el Señor. Porque tuve que regresar a esa apariencia
de gracia que primero me mostró el mal y la tentación,
(incluso después de muchos años de profesión cristiana) antes de que alguna
vez encontrara al Señor o volviera a sentir Su poder viviente.

Ahora, los sabios de esta era defienden su "`gracia común`" con la letra escrita,
donde dice que "`Él hace salir su sol sobre malos y buenos,
y que hace llover sobre justos e injustos;`"^
footnote:[Mateos 5:45]
y donde dice: "`Porque en él vivimos, y nos movemos, y somos.`"^
footnote:[Hechos 17:28]
Porque, ellos dicen, Dios les ha dado a todos salud,
fuerza y entendimiento en cosas naturales,
y capacidad para ver los pecados y los males más graves.
Pero eso que ellos llaman "`gracia especial`" es eso por
lo que los santos son salvos y establecidos en justicia,
y por lo cual el hombre recibe remisión de pecados.
Pero estos han fallado en ver que Aquel que hace salir Su sol, y que hace llover,
y da salud, fuerza y alimento a la creación externa y visible,
es el mismo que es la Vida del alma.
El mismo Poder que descubre los lugares oscuros de la horrible fosa,
guía a todos los que creen en ella a la tierra de los vivos.
El que muestra los pecados y los males más graves al hombre es el mismo que santifica,
purifica y salva a los que creen.
La misma virtud y poder que sostiene al hombre natural
es el que sostiene al hombre espiritual,
y aquello por lo cual vive para Dios.
Es la misma gracia, pero no digo que sea la misma medida.
Porque la virtud o el poder de Dios es lo que hizo todas las cosas vivientes y visibles,
y lo que las hace subsistir en su condición, pacto y límites donde están puestas.
Y de hecho, esta misma gracia, fuerza y poder, pero en una medida o grado superior,
es lo que preserva a todos los que creen, quienes han sido vivificados por Él,
y levantados para sentarse en lugares celestiales.
Incluso entre quienes creen, aunque la misma gracia obra en todos,
aun así puede haber una medida mayor de su pureza brillando en uno más que en otro,
rasgando el velo, haciendo que las sombras desaparezcan, esparciendo las nubes,
porque el corazón de este está más abierto para recibir su virtud.
Sin embargo, es la misma virtud y pureza,
y la gracia mantiene su pureza y propiedad en sí misma,
y su poder y suficiencia siempre son los mismos, aunque no le parezca así a la criatura.

Así que este es mi testimonio de la gracia de Dios, que es el don de Dios,
y que ha aparecido en cierta medida, más o menos, a todos los hombres:
La gracia de Dios es la que convence de los males obvios y excesivos,
y es la misma gracia que guía fuera del más pequeño pensamiento impuro,
de la incredulidad,
de la tentación y de los males secretos que se alojan en el corazón. De hecho,
toda la tierra será testigo de esta verdad en el Día de la aparición del Señor,
y ahora es experimentada por todos los hijos de la Luz que creen,
con quienes tengo comunión en la gracia pura, viviente, suficiente y perfecta de Dios.
Por lo tanto, todos se quedan sin excusa,
porque todos los que se vuelvan a Su gracia verán
que Él ha esperado largamente para tener piedad,
y para que toda la humanidad pueda ser partícipe de Su generosidad, amor,
misericordia y don de gracia,
por medio del cual la justificación viene sobre los que creen.
Escribo esto por el bien de aquellos quienes tienen sed de Dios y del conocimiento de Él,
y no para satisfacer a los hombres críticos,
ni a los que están en filosofía y en el engaño vano,
quienes están exaltados en su entendimiento carnal,
e hinchados por su propia mente terrenal.

Pero ahora voy a hablarles de eso que muchos dudan:
que si "`la gracia de Dios que se ha manifestado para salvación a todos
los hombres`" es o no un líder y un maestro suficiente cuando es recibida.
Que primero todos tomen nota de que cuando hablo
de la suficiencia de la gracia como un maestro,
no hablo de la gracia como algo distinto de Cristo,
o como algo separado del poder de Dios,
sino más bien como siendo uno con el poder y con Él de quién proviene.
Porque como Cristo es salvación en Sí mismo,
así también la gracia de Dios es de la misma naturaleza,
y por ella Él se manifiesta y a Su salvación a aquellos que creen,
revelando Su Testigo dentro de ellos.
Porque donde sea que la aparición y la presencia de Cristo se manifieste,
allí también se revela Su poder y fortaleza,
ya sea para salvación o para condenación. Y a pesar de que
Su aparición pura y presencia es una en sí misma,
aun así es formidable y terrible para aquellos que Lo han traspasado,
mientras es deseable, dulce, gloriosa y admirable para aquellos que han creído,
han sufrido con Él, y Lo han anhelado.
¡Oh, que todos los que Lo anhelan, Lo esperen con paciencia,
en esa luz donde Él aparecerá! Porque con seguridad Lo verán,
y contemplarlo será la recompensa de todo el anhelo, la sed, el deseo y la espera.
El sentido de anhelo y de estar sediento será quitado
cuando aparezca Aquel que alegra el corazón,
y alza la luz de Su rostro.
Por lo tanto, esperen todos, y no piensen que es mucho tiempo.
Mantengan sus mentes vueltas a Su gracia, que es Su aparición,
y entonces Lo sentirán y Lo verán, y serán satisfechos.
Y dirán, "`Éste es Él a quien hemos esperado, nos gozaremos y nos alegraremos;
porque ya ha llegado, y Su galardón está con Él.`"^
footnote:[Isaías 25:9; Isaías 62:11]

Ahora bien, Dios por Su amor eterno a los hijos de los hombres, ha seguido al hombre,
y lo ha llamado a regresar.
Sin embargo, hay una naturaleza en el hombre,
que se ha levantado por encima de la Vida y ha transgredido en Su contra,
y que siempre resiste los llamados del Señor. Porque no está sujeta a la ley de Dios,
ni a la gracia de Dios que enseña a negar la impiedad y los deseos mundanos.
Esta naturaleza ha rodeado a la criatura como una nube espesa,
y hace guerra contra el alma,
y no hay nadie que pueda librarla hasta que se escuche
la gracia que muestra la impiedad y los deseos mundanos.
Porque en verdad,
ninguno tiene poder o dominio sobre esa naturaleza en ellos que los lleva a la transgresión;
pero la gracia de Dios tiene poder en sí misma.
Verdaderamente, Dios quien es la salvación misma) se ha extendido desde Sí Mismo,
y ha aparecido en Su gracia pura y perfecta a todos los hombres, sin embargo,
no todos han recibido esta gracia.
Pues aunque el Señor ofrece la gracia para que la criatura
pueda recibirla y participar de su virtud y operación viva,
aun así mientras esa naturaleza que es contraria a la gracia, tenga preeminencia,
nunca la recibirá, sabiendo que la gracia de Dios la mortificará, tomará su vida,
y matará la enemistad.
Por lo tanto, todos deben estar quietos y en silencio,
y esperar en lo que es puro del Señor,
y sentir eso que recibe la gracia levantándose por encima de todos
los pensamientos y deseos corruptibles de la mente carnal.

Muchos que hablan de la gracia gratuita, no diferencian entre lo precioso y lo vil,
sino que animan a la gente a servir y a hacer obras cuando aún se encuentran en enemistad,
en la maldición y en la muerte.
Así han producido obras muertas, a pesar de todas sus actividades.
Porque ya que ellos están muertos a la vida de Dios, otro obra en ellos, es decir,
el que tiene el poder de la muerte, el cual es el diablo.
Y sin tener conocimiento de lo que es precioso en sí mismos,
no pueden ministrar hacia lo que es precioso en otros,
sino que son ministros de la muerte.

Ahora, aunque no todos han recibido la gracia, como para ser salvos de cometer pecado,
la falta no está en Dios.
Porque, "`Israel no quiso mi consejo; taparon sus oídos.`"^
footnote:[Proverbios 1:30; Zacarías 7:11]
La falta tampoco está en la gracia la cual ha aparecido a todos los hombres,
como si fuera demasiado débil o pequeña. Más bien,
la falta es que la gracia no es escuchada, esperada, ni obedecida, creída ni recibida.
Porque esta es la verdad eterna, que permanecerá por siempre:
La medida más pequeña de la gracia de Dios tiene poder en sí misma para
evitar que el hombre cometa el mal o el pecado que ella le muestra.
Y a medida que se recibe, el poder llega a manifestarse cada vez más,
y todos los que creen llegan a ser preservados del mal.

[.discourse-part]
Objeción: Pero ahora algunos dicen: "`Hay una gracia común y una gracia salvadora,
y la primera ha aparecido a todos,
pero la última ha aparecido solamente a los santos y a los elegidos.`"

[.discourse-part]
Respuesta: La gracia, que es el don puro y perfecto de Dios, es una sola cosa.
No estoy diciendo que la plenitud de la gracia ha aparecido a todos,
pero una medida de esta plenitud, que es Cristo, la Cabeza.
No obstante,
no puedo dividir la medida más pequeña de la plenitud en términos de calidad o naturaleza,
porque es una y la misma.
Porque la misma gracia que aleja a un hombre de la embriaguez y del exceso,
es tan pura y del mismo género y naturaleza como la mayor
proporción que aleja a un hombre de todo pecado.
Hablo de lo que he visto del Padre, aunque el mundo oscuro no puede recibirlo.
Porque la gente ha sido cegada y oscurecida con distinciones que
los hombres han creado y formulado en su razonamiento natural,
y por dotes naturales, los cuales están fuera de la Vida.
(Aunque no condeno habilidades naturales,
mientras se mantengan dentro de sus límites y alcances apropiados, es decir,
para la gestión de las cosas naturales en la creación visible.
Porque las cosas del reino de Dios son de otra calidad y naturaleza,
y no pueden ser alcanzadas por las habilidades naturales.)

[.discourse-part]
Objeción: Sin embargo, algunos estarán listos para decir, "`Esto es un error,
y es contrario a la Escritura y a los maestros ortodoxos,
sugerir que la gracia que salva está cerca de todos los hombres,
y ha aparecido a todos los hombres.`"

[.discourse-part]
Respuesta:
Aunque la gracia que ha aparecido a todos los hombres es salvadora en sí misma,
y puede llamarse verdaderamente gracia salvadora, sin embargo,
para los que no creen en ella, ni son enseñados por ella,
a estos la gracia sólo los convence y les muestra el mal,
reprende y condena por el pecado.
Sin embargo, no hay variación o cambio en la gracia misma,
porque la variación está en cómo obra en los diferentes objetos.
Porque la palabra de Su gracia es olor de vida para vida para los que creen,
y es olor de muerte para muerte para aquellos que no creen
(quienes en verdad están muertos mientras viven).
Aquí está la misma gracia, y sin embargo hay diferentes operaciones.
Porque "`Jehová mata y da vida,`"^
footnote:[1 Samuel 2:6]
pero es el mismo Señor. El mismo Espíritu que convence de pecado y lo reprueba,
también conforta y consuela.
Aquí hay diversidad de operaciones, sin embargo, es el mismo Espíritu que nunca cambia.

[.discourse-part]
Objeción: Más algunos pueden decir,
"`Si ha aparecido una medida de la gracia salvadora a todos los hombres,
entonces ¿cómo es que todos no son salvos por ella?`"

[.discourse-part]
Respuesta: No todos son salvos por ella, porque no creen en ella,
ni son enseñados por ella.
Y aunque los que son descuidados y desatentos dicen:
"`No sentimos poder o suficiencia en ella para salvarnos del pecado,`" aun así
esto no anula la confianza de aquellos que la han recibido y conocen su poder.
Porque hay poder y suficiencia en la gracia para hacer la voluntad de Dios.
Pero qué pasa si los no creyentes, ajenos de la vida dicen: "`No hay parecer en Cristo,
ni hermosura;`"^
footnote:[Isaías 53:2]
esto no hace que Su gloria sea nula quien es la imagen expresa del Padre,
lleno de gracia y verdad.
Los discípulos, que estuvieron en la fe vieron Su gloria, y dieron testimonio de Él;
pero los Fariseos, que eran incrédulos, dijeron: "`Demonio tiene.`"^
footnote:[Juan 10:20]

Por lo tanto, aquí está mi testimonio: La gracia de Dios, el don perfecto de Dios,
que muestra la impiedad y guía a todos los que son enseñados por él fuera de la impiedad,
es un maestro suficiente en sí mismo,
porque el poder de Cristo es manifiesto por medio de la gracia a todos los que lo escuchan.
Pablo, un ministro de la palabra de la reconciliación,
quien fue arrebatado hasta el tercer cielo donde vio cosas indecibles,
llegó a ser tentado y abofeteado por un mensajero de Satanás,
y el temor y la duda surgieron dentro de él. Tres veces le oró a Dios,
y esta respuesta le fue dada, "`Bástate mi gracia.`"^
footnote:[2 Corintios 12:9]
Por ende, es evidente para todos los entendimientos que han sido abiertos por el Señor,
que lo mismo que le mostró las tentaciones, y los mensajeros y abofeteadas de Satanás,
también era suficiente para preservarlo.
Así que la gracia es suficiente para todos los que
se aferran solamente a ella y se mantienen en ella,
suficiente para revelar la impiedad debido a su pureza,
alejar de deseos mundanos por su poder, enseñar la voluntad de Dios,
y vivir justamente en este siglo.
Este es el testimonio que doy de la gracia de Dios, incluso de lo que he sentido,
saboreado y palpado tocante su suficiencia, virtud y el poder de su operación,
testimonio que encomiendo a aquello que es de Dios en cada hombre,
lo cual dará testimonio de la verdad de mis palabras en el Día de Dios.
