== Sección XII.

[.blurb]
=== Una palabra para los hombres sabios del mundo, que se glorían en el sonido de las palabras, y adoran las apariencias externas, que desean escudriñar la cosas profundas de Dios por medio de su sabiduría, aprendizaje y estudio natural.

Dios está derramando Su poder y gloria, haciendo que fluya hacia Sus pequeños,
por los cuales todos ustedes son evaluados--todo su aprendizaje, lenguas, idiomas,
interpretaciones, significados y sabiduría, los cuales son sólo naturales.
Porque, a pesar de que hay muchos idiomas,
y cada uno tiene una interpretación y significado,
todos se quedan muy cortos para declarar la vida,
el ser inconmensurable de la vida eterna.
Oh sabios maestros, con sus retóricas, filosofías, disputas e idiomas,
no pueden conocer la mente del Espíritu o al Autor de la eterna salvación.
Y al no conocer por medio de estas cosas al eterno Espíritu viviente,
inventan, estudian, idean, forman y preparan cosas en sus mentes carnales.
De esta manera, llenan al mundo entero con sus concepciones oscuras y turbias,
llevando a los hombres lejos de la sabiduría viva de Dios,
la cual es mayor que sus palabras y lenguajes, y estaba antes que ellos.

Oh, el mundo ha tragado sus conceptos y distinciones,
sus fábulas artificiosas y adoraciones imaginadas,
y así muchos han perdido todo el sentido de Dios en sí mismos para ser guiados,
y por lo tanto ahora están más lejos del verdadero conocimiento
de Dios que el día que salieron del vientre de su madre.
Oh, qué lamentable es ver cuántos han salido de la simplicidad pura que está en Cristo,
hacia la sutileza y el engaño,
y que ahora están atestados y llenos de lo que debe ser derramado como agua antes de
que puedan llegar a la menor medida del conocimiento verdadero y salvador de Dios.
Oh, un Día terrible viene sobre ustedes como ladrón,
porque han quitado la llave del conocimiento,
y le han dado a la gente lo que no puede abrir.
Ustedes y los que le siguen, serán excluidos como necios, aunque se consideren sabios.
En verdad, su sabiduría perecerá, y su honor yacerá en el polvo.

Y ustedes,
profesantes literales del cristianismo que han metido la Escritura en sus cabezas,
y en sus mentes carnales para hablar de ellas,
¡cuánto han tomado y exaltado las prácticas visibles
y figurativas pero han rechazado la vida!
Están haciendo ídolos de esas cosas que no fueron
sino figuras y representaciones en su tiempo.
Y ustedes,
como los fariseos están limitando al Señor. Porque si Él no se les aparece
de acuerdo con lo que han prescrito y reunido de la letra escrita,
entonces no Lo recibirán. Porque han amontonado sus
interpretaciones en la parte carnal del hombre,
la cual se ha levantado como una montaña dentro de ustedes,
muy por encima del Testigo puro de Dios en ustedes, muy por encima de Su aparición,
de modo que han perdido de vista eso que les podría dar conocimiento del Dios viviente,
y hacerlos conscientes de Su presencia pura.
Que el Señor abra su entendimiento, para que puedan verse a sí mismos,
y que tan caprichosos, vanos,
ligeros y desvergonzados son y cómo son uno con el
mundo en todas las cosas en su misma fuente.
Alegan libertad en Cristo, y privilegios en Él,
incluso mientras son aún esclavos de la corrupción y de muchas codicias dañosas.

Consideren, que todas las apariciones externas son como una cortina, o velo,
o sombra en comparación con Cristo, que es la justicia de Dios interna.
Pero ustedes están tan llenos de sus aprehensiones de Su justicia como
algo lejos de ustedes que han olvidado la condición de su propia casa.
Porque en verdad, la justicia de Cristo no será un manto para su justicia propia,
ni para su injusticia.
Y si Cristo no está formado en ustedes, y no vive en ustedes, ni actúa en ustedes,
ni obra Su obra en ustedes, entonces están en la justicia propia.
Y todo lo que hablen de imputación no los salvará mientras
no estén en esa naturaleza y fe que es contada por Su justicia.
¿No están cansados de ser llevados por doquier entre
las colinas terrenales que ustedes mismos han formado?
¿No ven que su tierra se ha vuelto estéril, y sus posesiones se han secado,
y su adoración ha muerto, y que las lluvias y el rocío del cielo no caen sobre ustedes,
sino que en lugar de esto se marchitan diariamente como una rama sin savia?
¿Qué han encontrado que dure hasta la eternidad?
¿Oh, no está ya oxidado y se está desvaneciendo?
¿No está ya corroído y comido por la polilla?
La gloria de todas las cosas terrenales se desvanece, y todas las apariciones terrenales,
a pesar de ser tan gloriosas, cesarán. No habrá ya más gloria en estas cosas,
porque éstas volarán como una sombra cuando el sol salga.
Sus riquezas se están desperdiciando, pero ¿cuándo buscarán eso que perdura para siempre?

Me compadezco de los que han tenido verdaderos anhelos en pos de Dios,
pero se han sentado satisfechos en eso que no es eterno.
Les advierto,
¡vuelvan a casa! ¿Descansan en una fe que dice que
nunca serán limpiados aquí? Esa fe es maldita,
es reprobada, más bien se llama incredulidad.
No es la fe de los escogidos de Dios,
por la cual fueron santificados y vencieron al maligno
en sí mismos por el poder de Cristo.
Porque Cristo puede salvar y manifestar Su habilidad en todos los que creen en la luz.
De hecho, Cristo se manifiesta a Sí mismo a la criatura,
y da a conocer Su poder en la criatura,
para redimir al alma de la muerte y de la esclavitud de corrupción,
para servir en el Espíritu libre de Dios, en el cual los hijos son libertados del pecado,
convirtiéndose en templos del Espíritu Santo.
Consideren qué tan lejos se encuentran de esto,
ustedes que todavía son templos de inmundicia y habitaciones de deseos mortales.
Porque de verdad, establecer una práctica visible y externa, y conformarse a ella,
no los justificará mientras aquello que ha transgredido la Vida
y desobedecido la Luz todavía siga siendo la cabeza en ustedes,
y aún esté levantado por encima de lo que es puro.
Deben venir a la Roca antes de que conozcan cualquier cosa que permanezca,
o cualquier cosa sobre la cual construir--cuya Roca es Cristo,
que permanece para siempre.
Pero ustedes se han ido de eso que puede darles el conocimiento de Dios en ustedes mismos,
esto es, la Luz de Su Espíritu, que brilla en sus corazones,
manifestando las intenciones del corazón y las tendencias hacia mal.

El tiempo de la restauración ha llegado,
y muchos son restaurados nuevamente al pacto de Dios.
Muchos han sido librados de los colmillos de la muerte,
y sentido a Aquel quien es el reparador de portillos
como el restaurador de los lugares desolados.
Pero todos tienen que experimentar la desolación
de ese lugar donde la naturaleza salvaje se aloja,
antes de que participen en la restauración. Entonces vengan,
desciendan de las montañas estériles donde están siendo alimentados.
Vengan a Cristo, la Vida de los hombres, quien los ha iluminado,
para que puedan sentir Su mente en sí mismos.
De lo contrario, continuarán errando por falta de conocimiento,
y perecerán por falta de entendimiento, y en dolor serán sepultados.
