== Sección XIII.

[.blurb]
=== El reino de Dios y de Cristo declarados en cierta medida, qué es, dónde debe esperarse, y cómo se revela internamente a los que creen.

El Señor ha preparado Su trono en los cielos, Su reino gobierna sobre todo,
y Su dominio es un dominio eterno.
Dios es Espíritu, Su reino es espiritual, Su morada corresponde a Su propia naturaleza.
Él es inmortal, Su reino es así. Él es Luz,
Su morada también lo es--una morada pura donde no hay inmundicia,
ni nunca habrá. Consiste en pureza y deleite, en poder, justicia, gozo, esperanza, paz,
vida, tranquilidad y virtud eterna.
Es una morada de quietud, eternamente gloriosa, incomprensible, inescrutable e indecible.
Las palabras se quedan muy cortas; no son más que sonidos, y son como velos.
Todos los que creen en el Rey de gloria eterna e inmortal llegan a recibir de Su sabiduría,
de Su vida, de Su poder, virtud, justicia,
y a disfrutar de Aquel que es la plenitud que llena todas las cosas,
ya sean visibles o invisibles, terrenales o celestiales.

Oh, pero estas cosas están escondidas del mundo,
de aquellos que no son redimidos de la tierra,
ni intentan serlo mientras están en el cuerpo.
A tales digo,
nunca verán o disfrutarán del reino de Dios mientras permanezcan en una fe que es reprobada,
en una fe que verdaderamente puede llamarse incredulidad.
A pesar de que imaginen una gloria y reino en su mente terrenal,
y sueñen con algo por venir (que corresponde a esa
naturaleza en la que ahora está su gloria),
sin embargo, todo esto fallará,
y esas imaginaciones serán confundidas y disueltas en nada.
Estos sueños están fuera de la verdad, fuera de Cristo,
y por lo tanto están sin base o fundamento,
y están fuera de eso que les daría visión y entendimiento de Dios y de Su reino.

Cuando Cristo enseñó a aquellos que Lo seguían,
los exhortó a "`buscar primeramente el reino de Dios,`"^
footnote:[Mateos 6:33]
incluso mientras estaban en el cuerpo.
Los fariseos miraban hacia afuera con su conocimiento terrenal,
y aunque tenían las Escrituras que declaraban el reino de Dios, aun así no lo conocieron.
Y ahora esta generación es igual, están en la misma naturaleza, y en la misma sabiduría,
que es terrenal y literal.
Están imaginando, como lo estaban haciendo los judíos, y diciendo "`helo aquí,
o helo allá,`" el reino está en este ritual, y en esta cosa.
No, Cristo dijo, "`el reino de Dios dentro de vosotros está,`"^
footnote:[Lucas 17:21 RV1602 Purificada]
y les ordenó que lo buscaran primeramente.
"`¿Qué extraña doctrina es esta?`"
pudieron haber dicho los fariseos.
"`¡Él dice que el reino está dentro de nosotros,
y sin embargo nos manda a buscarlo! ¿Debemos buscar eso que ya está en nosotros?`"
Sí, es como una perla o un tesoro escondido en un campo.
Es como un grano de mostaza entre muchas otras semillas, que no se encuentra fácilmente.
Es como una moneda de plata perdida entre mucha suciedad en la casa,
y no la van a encontrar hasta que esta suciedad sea barrida.
Tienen que escarbar profundo, barrer completamente, buscar cuidadosamente,
antes de encontrarla.
Y a pesar de que Él les dijo a los fariseos "`el reino de Dios
dentro de vosotros está,`" no dijo que fueran poseedores de él,
o que les perteneciera.
Sin embargo, a los discípulos,
a quienes Él les enseñó a orar en fe "`Venga tu reino,`"
estos encontraron aquello por lo que oraron--la perla,
la moneda, el grano de mostaza.
Y habiéndolo encontrado, y creyendo en Él, les dijo:
"`Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos.`"
Y en Lucas 6:20 dice: "`Y alzando los ojos hacia sus discípulos, decía:
Bienaventurados vosotros los pobres, porque vuestro es el reino de Dios.`"
Lo habían visto, y lo poseían; en verdad era de ellos.
Asimismo Cristo le dijo a Sus discípulos: "`Hay algunos de los que están aquí,
que no gustarán la muerte, hasta que hayan visto el reino de Dios venido con poder.`"^
footnote:[Mateos 16:28; Marcos 9:1; Lucas 9:27]
Ciertamente, sus palabras fueron cumplidas,
porque ellos declararon lo que habían sentido y visto, y algunos de ellos dijeron:
"`El reino de Dios no consiste en palabras, sino en poder.`"^
footnote:[1 Corintios 4:20]
Además Pablo escribió a los romanos (quienes también fueron hechos participantes
del mismo poder y reino) que "`el reino de Dios no es comida ni bebida,
sino justicia, paz y gozo en el Espíritu Santo.`"^
footnote:[Romanos 14:17]
Y de los colosenses que habían esperado el reino,
y creído en esa luz por la cual fue revelado, se dice,
"`dando gracias al Padre que nos hizo aptos para
participar de la herencia de los santos en luz;
el cual nos ha librado de la potestad de las tinieblas,
y trasladado al reino de su amado Hijo.`"^
footnote:[Colosenses 1:12-13]
Estas cosas fueron vistas incluso en el cuerpo, y experimentadas en el cuerpo.
Asimismo el apóstol dijo a los hebreos: "`El que cree entra en el reposo.`"^
footnote:[Hebreos 4:3]
Ahora, todas estas cosas se sienten internamente por la Semilla inmortal,
el nacimiento inmortal,
y por aquellos que experimentan este nacimiento inmortal viviendo en ellos.
Así que todo el que alguna vez llegue a ver y a sentir el reino de Dios,
el cual es espiritual, debe esperar en el Espíritu, y en su manifestación.

[.discourse-part]
Objeción: Pero algunos dicen que hay dos tipos de reino--uno de gracia aquí y ahora,
y otro de gloria en el porvenir,
el cual nadie llega a gozar en esta vida o en este cuerpo.

[.discourse-part]
Respuesta:
Por mucho tiempo las personas han estado cegadas
y confundidas con los nombres y las palabras,
y siendo llenos de pensamientos y conceptos imaginarios han generado distinciones absurdas;
e intentan separar lo que Dios ha unido.
La gracia es gloriosa, y la gloria está llena de gracia, no están separadas.
El reino de Dios, el cual fue una vez como un grano de mostaza,
se volvió más tarde en un gran árbol.
Y aunque el árbol en su fuerza,
gloria y altura es más glorioso que cuando estaba en la semilla,
aun así la semilla y el árbol son uno en naturaleza, calidad y género.
Donde el reino de Dios gobierna en pureza, poder y gloria, ¿ahí no hay unidad?
Aunque haya medidas mayores, ¿acaso no hay un solo dominio, un poder, una gloria,
un reino en el que existen tanto la gracia como la gloria?
La gracia es verdaderamente gloriosa,
"`habiéndonos predestinado para ser adoptados como
hijos suyos para alabanza de la gloria de su gracia,
con la cual nos hizo aceptos en el Amado.`"^
footnote:[Efesios 1:5-6]
Y es por medio de la gracia que la gloria llega a ser revelada
en la tierra-- "`Toda la tierra está llena de su gloria.`"^
footnote:[Isaías 6:3]
Porque Dios está revelando Su poder, Su reino,
Su gracia y Su gloria a todos los que esperan pacientemente en Él,
en eso que aún puede ser como un grano de mostaza.
Estos llegarán a sentir Su presencia,
Su poder y gloria revelados en el corazón por medio del Espíritu,
y gozarán a Dios en Su reino, poder, y gloria,
y por medio de la fe verán el peso de la gloria.

[.discourse-part]
Objeción: Sin embargo, algunos dirán, ¿Qué?,
¿no buscan ninguna otra gloria además de la que se obtiene en esta vida?
¿Ni ningún otro reino sino el que gozan en esta vida?

[.discourse-part]
Respuesta:
Los santos no buscaron ninguna otra gloria diferente
de aquella que se encuentra en la vida eterna,
en la vida inmortal e incorruptible,
y la patria que buscaban era aquella cuyo arquitecto y constructor es Dios.
Estos buscaron y esperaron para recibir de Su poder,
el poder en el que el reino consiste,
y llegaron a conocerlo y disfrutarlo en esta vida
(aunque no digo que todo el peso de la gloria).
Porque hacerse partícipes de Su eterno dominio y
autoridad es lo que todos los santos experimentaron,
y con el tiempo llegaron a gozarlo por medio de la fe.
Porque por la fe vieron Al que era invisible, y las cosas de Su reino,
las cuales son invisibles, espirituales y eternas.
Pero la vida corruptible de la carne, la de aquellos que están muertos mientras viven,
esa vida no conoce el reino, ni el poder, ni la gloria.
La gloria de Dios no es revelada al hombre hasta después de la muerte de esa vida,
y la muerte del que tiene el poder de la muerte, el cual es el diablo,
quien gobierna en los corazones de los hijos de desobediencia.
De hecho,
el reino de Dios está oculto de los ojos de todos mientras permanecen en ese estado.

Pero bienaventurado es el oído que puede escuchar,
porque el reino de Dios se ha acercado a muchos,
y la salvación de Dios y el poder de Su Cristo son vistos por muchos.
Honor y alabanza para Él por siempre, que es el único soberano,
y quien pone bajo Sus pies toda autoridad, para que el Señor sea todo en todos.
Sin embargo, primero todos deben llegar a sentir el reino de Dios en sí mismos,
que comienza como un pequeño grano dentro de ellos.
El hombre debe llegar a creer en esto antes de que pueda conocer
verdaderamente el reino, o en qué consiste.
E incluso después de ser conocido en cierta medida,
la medida aún se queda muy corta de la plenitud de la gloria.
Porque en verdad, muchos pueden llegar a ser participantes del poder en cierta medida,
pero la medida está muy corta del eterno peso de gloria.

"`El que cree, ha entrado en el reposo,`" y se hace partícipe del don celestial,
del poder celestial, de la gracia celestial (todo lo cual es glorioso),
y en verdad experimenta el lugar celestial en Cristo Jesús. Y aun así,
sigue habiendo muchos enemigos que tienen que ser sojuzgados,
y todavía hay mucho de la morada celestial que no se ha visto.
Estos llegan a ser revelados en tanto que haya una permanencia en la fe,
que está en el poder de Dios.
En efecto,
los misterios de Dios y de Su reino llegan a ser revelados en el debido tiempo;
llegan a ser conocidos por medio de la muerte, es decir,
a través de la muerte de la muerte.
Porque en el caso de Israel, el verdadero tipo,
después de que pasaron sobre el Jordán y tomaron a Jericó y a Hai,
y entraron a la tierra, aún quedaban muchos enemigos por someter,
y mucha tierra por poseer,
que no disfrutaron hasta mucho tiempo después. De la misma manera, ahora,
después de que se disfruta y posee un verdadero descanso,
y una entrada al reino es otorgada, aun así hay muchos enemigos por ser sometidos,
y aún mucha herencia celestial para ser disfrutada por aquellos
que permanecen en el poder que da dominio sobre el pecado,
el diablo, el infierno y el sepulcro.
Estos son hechos partícipes de Dios, y según la enemistad es matada,
gozan de Dios (que es vida eterna).
Estos llegan a recibir la corona inmortal,
la cual Dios da en Su debido tiempo a aquellos que esperan con paciencia y fe,
a través de los cuales la herencia inmortal se revela a todos los hijos de la luz.

Y para concluir en pocas palabras, digo esto a todos los que anhelan a Dios,
y esperan sentir Su poder:
Mantengan sus mentes vueltas a la medida pura del Espíritu Santo de Dios,
y esperen allí para ver Su reino y dominio,
y ser participantes de él. Porque este reino lleva el mundo a su fin,
y les permitirá ver también el fin de este mundo, y antes de que existiera,
y también al Único que ahora es glorificado con el Padre en el reino de Dios
con la misma gloria que Él tuvo con el Padre antes de la fundación del mundo.
Y quienquiera que llegue al fin del mundo, y al verdadero comienzo,
llega a verlo a Él en Su gloria, y al reino de gloria que no se marchita.
Ciertamente, todos los que llegan a gozar de esto son felices eternamente.
